/* VCT Hospital OS 5.0-r08 — Stage 3 Deep Case Workspace
 * A continuous encounter workspace: history -> exam -> diagnostics -> diagnosis -> treatment -> Rx -> nursing/orders -> follow-up -> progress notes.
 * Uses original VCT data structures; no third-party code/UI copied.
 */
(function(){'use strict';
 const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const read=(k,d)=>{try{const x=JSON.parse(localStorage.getItem(k));return x==null?d:x}catch{return d}};
 const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const flow=()=>read('VCT_OUTPATIENT_FLOW20_V1',[]);
 const current=()=>{const a=flow(),id=localStorage.getItem('VCT_ACTIVE_ENCOUNTER_V1');return a.find(x=>x.id===id)||null};
 const now=()=>new Date().toISOString();
 function save(x){x.updatedAt=now();const a=flow();const i=a.findIndex(q=>q.id===x.id);if(i>=0)a[i]=x;write('VCT_OUTPATIENT_FLOW20_V1',a);}
 function audit(action,meta){const a=read('VCT_HIS_PRO_AUDIT_V1',[]);a.unshift({time:now(),actor:read('VCT_HIS_ROLE','doctor'),action,meta});write('VCT_HIS_PRO_AUDIT_V1',a.slice(0,5000));}
 function install(){if($('#vctStage3Style'))return;const s=document.createElement('style');s.id='vctStage3Style';s.textContent=`
 .vct3{display:grid;grid-template-columns:minmax(0,1fr) 285px;gap:10px}.vct3-main{min-width:0}.vct3-rail{min-width:0;position:sticky;top:10px;align-self:start}
 .vct3-head{background:#fff;border:1px solid #d9e2e6;border-radius:11px;padding:11px;margin-bottom:9px}.vct3-headline{display:flex;justify-content:space-between;gap:10px;align-items:center}.vct3-name{font-size:18px;font-weight:800}.vct3-meta{font-size:10px;color:#7b8990;margin-top:3px}.vct3-tags{display:flex;gap:4px;flex-wrap:wrap;margin-top:6px}.vct3-tag{font-size:10px;padding:3px 7px;border-radius:999px;background:#eef3f4}
 .vct3-tabs{display:flex;gap:2px;overflow:auto;background:#fff;border:1px solid #d9e2e6;border-radius:9px;padding:3px;margin-bottom:9px}.vct3-tabs button{border:0;background:transparent;padding:8px 10px;white-space:nowrap;font-size:11px;color:#56656c;border-radius:6px;cursor:pointer}.vct3-tabs button.active{background:#e9f6f3;color:#0f766e;font-weight:800}
 .vct3-card{background:#fff;border:1px solid #d9e2e6;border-radius:10px;padding:11px;margin-bottom:9px}.vct3-card h3{margin:0 0 8px;font-size:13px}.vct3-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.vct3-grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.vct3-field label{display:block;font-size:10px;color:#718087;margin-bottom:3px}.vct3-field input,.vct3-field select,.vct3-field textarea{width:100%;box-sizing:border-box;border:1px solid #ccd7dc;border-radius:6px;padding:7px;font-size:11px;background:#fff}.vct3-field textarea{min-height:65px;resize:vertical}.vct3-section{border:1px solid #e1e7ea;border-radius:8px;padding:8px;margin-top:7px}.vct3-section b{font-size:11px}.vct3-systemgrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:5px;margin-top:6px}.vct3-systemgrid label{font-size:10px;color:#56656c;border:1px solid #e3e8eb;border-radius:6px;padding:5px;background:#fafcfc}.vct3-systemgrid input{width:100%;border:0;border-bottom:1px solid #d8e0e4;font-size:10px;box-sizing:border-box;margin-top:3px;background:transparent}
 .vct3-table{width:100%;border-collapse:collapse;font-size:10px}.vct3-table th,.vct3-table td{border-bottom:1px solid #e5eaed;padding:6px;text-align:left;vertical-align:top}.vct3-table th{background:#f7f9fa}.vct3-btn{border:1px solid #d3dee2;background:#fff;border-radius:6px;padding:6px 9px;font-size:10px;cursor:pointer}.vct3-btn.primary{background:#0f766e;color:#fff;border-color:#0f766e}.vct3-btn.danger{background:#fff5f5;color:#a33;border-color:#ecc}.vct3-actions{display:flex;gap:5px;flex-wrap:wrap}.vct3-checks{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:5px}.vct3-checks label{font-size:10px;border:1px solid #e1e7ea;border-radius:6px;padding:6px}.vct3-checks input{margin-right:4px}.vct3-note{border-left:3px solid #9fbfc0;background:#f8fbfb;padding:7px;font-size:10px;margin-top:6px}.vct3-alert{background:#fff7e8;border:1px solid #f0d39c;border-radius:7px;padding:7px;font-size:10px}.vct3-ok{background:#eef9f1;border:1px solid #c7e4cf;border-radius:7px;padding:7px;font-size:10px}.vct3-timeline{border-left:2px solid #dbe5e7;margin-left:5px;padding-left:11px}.vct3-event{position:relative;margin-bottom:9px}.vct3-event:before{content:'';position:absolute;left:-17px;top:4px;width:7px;height:7px;border-radius:50%;background:#0f766e}.vct3-event time{font-size:9px;color:#89969c}.vct3-event b{font-size:10px;display:block}.vct3-event div{font-size:10px;color:#5e6b72;white-space:pre-wrap}.vct3-footer{position:sticky;bottom:0;z-index:6;background:rgba(255,255,255,.97);border-top:1px solid #d9e2e6;padding:7px;display:flex;justify-content:flex-end;gap:6px}.vct3-rail .vct3-card{font-size:10px}.vct3-rail .vct3-action{display:block;width:100%;text-align:left;border:1px solid #d8e1e5;background:#fff;border-radius:7px;padding:7px;margin:4px 0;font-size:10px;cursor:pointer}
 @media(max-width:1050px){.vct3{grid-template-columns:1fr}.vct3-rail{position:static}.vct3-systemgrid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.vct3-grid,.vct3-grid2{grid-template-columns:1fr}.vct3-checks{grid-template-columns:1fr}.vct3-systemgrid{grid-template-columns:1fr}}
 `;document.head.appendChild(s)}
 const defExam={temperature:'',weight:'',breathe:'',heartrate:'',bloodPressure:'',bcs:'',mentation:'',hydration:'',mucous:'',crt:'',pain:'',eyes:'',ears:'',nose:'',oral:'',skin:'',lymph:'',heart:'',lung:'',abdomen:'',musculoskeletal:'',neurologic:'',urogenital:''};
 const defDx={primary:'',secondary:[],differentials:[],certainty:'工作诊断',basis:'',problemList:[]};
 const defPlan={goals:'',treatment:'',monitoring:'',nursing:'',clientInstructions:'',prognosis:'',restrictions:''};
 function ensure(x){x.medical=x.medical||{};const m=x.medical;m.examStructured={...defExam,...(m.examStructured||{})};m.diagnosisStructured={...defDx,...(m.diagnosisStructured||{})};m.planStructured={...defPlan,...(m.planStructured||{})};m.diagnosticOrders=Array.isArray(m.diagnosticOrders)?m.diagnosticOrders:[];m.progressNotes=Array.isArray(m.progressNotes)?m.progressNotes:[];m.nursingOrders=Array.isArray(m.nursingOrders)?m.nursingOrders:[];m.doctorOrders=Array.isArray(m.doctorOrders)?m.doctorOrders:[];m.followupPlan=m.followupPlan||{date:'',channel:'电话',purpose:'',redFlags:'',status:'待安排'};return m}
 function saveField(x,key,val){const m=ensure(x);m[key]=val;save(x)}
 function render(){install();const x=current();const body=$('#hisproBody');if(!x||!body)return false;const m=ensure(x),p=x.pet||{},c=x.customer||{};body.dataset.vct3='1';body.innerHTML=`<div class="vct3">
 <div class="vct3-main"><div class="vct3-head"><div class="vct3-headline"><div><div class="vct3-name">${esc(p.name||'患者')}</div><div class="vct3-meta">${esc(p.species||'')} · ${esc(p.breed||'')} · ${esc(p.sex||'')} · ${esc(p.age||'')} · 主人：${esc(c.name||'')}</div></div><div class="vct3-actions"><button class="vct3-btn" id="v3Save">保存</button><button class="vct3-btn primary" id="v3Finalize">完成接诊</button></div></div><div class="vct3-tags"><span class="vct3-tag">${esc(x.mrn||'')}</span><span class="vct3-tag">${esc(x.registration?.visitType||'门诊')}</span><span class="vct3-tag">${esc(x.queue?.status||x.status||'')}</span><span class="vct3-tag">医生：${esc(x.queue?.vet||'未分配')}</span></div></div>
 <div class="vct3-tabs" id="v3tabs">${[['summary','病例总览'],['history','病史'],['exam','体格检查'],['diagnostic','检验 / 影像'],['diagnosis','诊断 / 鉴别'],['treatment','治疗 / 处置'],['rx','处方 / 医嘱'],['nursing','护理 / 病程'],['followup','回访 / 复诊']].map(([id,l],i)=>`<button data-v3tab="${id}" class="${i===0?'active':''}">${l}</button>`).join('')}</div><div id="v3content"></div><div class="v3footer-placeholder"></div></div>
 <aside class="vct3-rail"><div class="vct3-card"><h3>当前病例状态</h3><div id="v3state"></div></div><div class="vct3-card"><h3>病例快速操作</h3><button class="vct3-action" data-v3go="history">补全病史</button><button class="vct3-action" data-v3go="exam">录入体检</button><button class="vct3-action" data-v3go="diagnostic">开检查</button><button class="vct3-action" data-v3go="diagnosis">建立诊断</button><button class="vct3-action" data-v3go="treatment">建立治疗计划</button><button class="vct3-action" data-v3go="rx">处方 / 医嘱</button><button class="vct3-action" data-v3go="nursing">病程 / 护理</button><button class="vct3-action" data-v3go="followup">安排回访</button></div><div class="vct3-card"><h3>时间轴</h3><div id="v3timeline"></div></div></aside></div>`;
 const tabs=$$('#v3tabs [data-v3tab]');tabs.forEach(b=>b.onclick=()=>{tabs.forEach(q=>q.classList.remove('active'));b.classList.add('active');renderTab(b.dataset.v3tab,x,m)});$$('[data-v3go]').forEach(b=>b.onclick=()=>{const t=tabs.find(q=>q.dataset.v3tab===b.dataset.v3go);t?.click();});$('#v3Save').onclick=()=>{save(x);audit('SAVE_CASE_WORKSPACE',{id:x.id});window.toast?toast('病例已保存'):alert('病例已保存')};$('#v3Finalize').onclick=()=>finalize(x);renderTab('summary',x,m);renderState(x,m);renderTimeline(x,m);return true}
 function renderTab(t,x,m){const c=$('#v3content');if(!c)return;const set=(k,v)=>{m[k]=v;save(x)};
 if(t==='summary'){c.innerHTML=`<div class="vct3-card"><h3>本次就诊摘要</h3><div class="vct3-grid2"><div class="vct3-field"><label>主诉</label><textarea id="v3chief">${esc(x.registration?.chief||m.chief||'')}</textarea></div><div class="vct3-field"><label>当前临床摘要</label><textarea id="v3summary">${esc(m.summary||'')}</textarea></div></div><div class="vct3-note">病例工作区原则：同一当前就诊内完成病史、检查、诊断、治疗、医嘱、文书与随访；跨就诊历史保留在患者主档。</div></div><div class="vct3-card"><h3>问题清单</h3><div id="v3problems"></div><div class="vct3-actions"><input id="v3problem" placeholder="新增问题" style="flex:1;padding:7px;border:1px solid #ccd7dc;border-radius:6px;font-size:10px"><button class="vct3-btn" id="v3addproblem">添加</button></div></div>`;$('#v3chief').onchange=e=>{x.registration=x.registration||{};x.registration.chief=e.target.value;save(x)};$('#v3summary').onchange=e=>set('summary',e.target.value);const probs=m.diagnosisStructured.problemList||[];$('#v3problems').innerHTML=probs.map((q,i)=>`<span class="vct3-tag">${esc(q)} <button data-delp="${i}" style="border:0;background:none;cursor:pointer">×</button></span>`).join('')||'<span style="font-size:10px;color:#89969c">暂无问题清单</span>';$$('[data-delp]').forEach(b=>b.onclick=()=>{probs.splice(+b.dataset.delp,1);m.diagnosisStructured.problemList=probs;save(x);renderTab(t,x,m)});$('#v3addproblem').onclick=()=>{const v=$('#v3problem').value.trim();if(v){probs.push(v);m.diagnosisStructured.problemList=probs;save(x);renderTab(t,x,m)}}}
 if(t==='history'){c.innerHTML=`<div class="vct3-card"><h3>结构化病史</h3><div class="vct3-grid2">${[['history','现病史'],['past','既往史 / 用药史'],['prevent','疫苗 / 驱虫史'],['allergy','过敏史'],['diet','饮食 / 环境'],['exposure','暴露 / 旅行 / 接触史']].map(([k,l])=>`<div class="vct3-field"><label>${l}</label><textarea data-hist="${k}">${esc(m[k]||x.registration?.[k]||'')}</textarea></div>`).join('')}</div></div>`;$$('[data-hist]').forEach(e=>e.onchange=()=>set(e.dataset.hist,e.value));return}
 if(t==='exam'){const e=m.examStructured;c.innerHTML=`<div class="vct3-card"><h3>生命体征 / 基础检查</h3><div class="vct3-grid">${[['temperature','体温 °C'],['weight','体重 kg'],['breathe','呼吸 次/min'],['heartrate','心率 次/min'],['bloodPressure','血压'],['bcs','BCS'],['mentation','意识'],['hydration','脱水'],['mucous','黏膜'],['crt','CRT'],['pain','疼痛评分']].map(([k,l])=>`<div class="vct3-field"><label>${l}</label><input data-ex="${k}" value="${esc(e[k])}"></div>`).join('')}</div></div><div class="vct3-card"><h3>系统性体格检查</h3><div class="vct3-systemgrid">${[['eyes','眼'],['ears','耳'],['nose','鼻/上呼吸道'],['oral','口腔'],['skin','皮肤/被毛'],['lymph','淋巴结'],['heart','心血管'],['lung','呼吸系统'],['abdomen','腹部'],['musculoskeletal','肌骨'],['neurologic','神经'],['urogenital','泌尿生殖']].map(([k,l])=>`<label>${l}<input data-ex="${k}" value="${esc(e[k])}"></label>`).join('')}</div><div class="vct3-field" style="margin-top:8px"><label>体检综合异常</label><textarea data-ex="overall">${esc(e.overall||m.exam||'')}</textarea></div></div>`;$$('[data-ex]').forEach(q=>q.onchange=()=>{e[q.dataset.ex]=q.value;m.exam=e.overall||'';save(x)});return}
 if(t==='diagnostic'){const arr=m.diagnosticOrders;c.innerHTML=`<div class="vct3-card"><h3>检查申请 / 结果闭环</h3><div class="vct3-grid2"><div class="vct3-field"><label>项目</label><input id="v3testname" placeholder="CBC / 生化 / PCR / X-ray / 超声…"></div><div class="vct3-field"><label>目的 / 临床问题</label><input id="v3testreason"></div></div><div class="vct3-actions" style="margin:7px 0"><button class="vct3-btn primary" id="v3addtest">添加检查</button></div><table class="vct3-table"><thead><tr><th>时间</th><th>项目</th><th>目的</th><th>状态</th><th>结果/解读</th><th></th></tr></thead><tbody>${arr.map((q,i)=>`<tr><td>${esc(q.time?.slice(0,16)||'')}</td><td>${esc(q.name)}</td><td>${esc(q.reason)}</td><td><select data-teststate="${i}"><option ${q.status==='已完成'?'selected':''}>已完成</option><option ${q.status!=='已完成'?'selected':''}>待结果</option></select></td><td><textarea data-testresult="${i}" style="min-width:180px">${esc(q.result||'')}</textarea></td><td><button class="vct3-btn danger" data-testdel="${i}">删除</button></td></tr>`).join('')}</tbody></table><div class="vct3-note">检验、影像结果应保留项目、结果、报告时间与报告人员等正式记录；这里是病例工作区的临床整合层。</div></div>`;$('#v3addtest').onclick=()=>{const n=$('#v3testname').value.trim();if(!n)return;arr.push({id:'T'+Date.now(),time:now(),name:n,reason:$('#v3testreason').value.trim(),status:'待结果',result:''});save(x);renderTab(t,x,m)};$$('[data-teststate]').forEach(q=>q.onchange=()=>{arr[+q.dataset.teststate].status=q.value;save(x)});$$('[data-testresult]').forEach(q=>q.onchange=()=>{arr[+q.dataset.testresult].result=q.value;save(x)});$$('[data-testdel]').forEach(q=>q.onclick=()=>{arr.splice(+q.dataset.testdel,1);save(x);renderTab(t,x,m)});return}
 if(t==='diagnosis'){const d=m.diagnosisStructured;c.innerHTML=`<div class="vct3-card"><h3>临床诊断</h3><div class="vct3-grid2"><div class="vct3-field"><label>主要诊断 / 当前工作诊断</label><input id="v3primary" value="${esc(d.primary)}"></div><div class="vct3-field"><label>诊断确定程度</label><select id="v3certainty"><option ${d.certainty==='工作诊断'?'selected':''}>工作诊断</option><option ${d.certainty==='高度疑似'?'selected':''}>高度疑似</option><option ${d.certainty==='确诊'?'selected':''}>确诊</option><option ${d.certainty==='排除'?'selected':''}>排除</option></select></div></div><div class="vct3-field" style="margin-top:7px"><label>诊断依据</label><textarea id="v3basis">${esc(d.basis)}</textarea></div><div class="vct3-field" style="margin-top:7px"><label>鉴别诊断（每行一个，按优先级）</label><textarea id="v3ddx">${esc((d.differentials||[]).join('\n'))}</textarea></div><div class="vct3-field" style="margin-top:7px"><label>伴随/次要诊断（每行一个）</label><textarea id="v3secondary">${esc((d.secondary||[]).join('\n'))}</textarea></div></div><div class="vct3-card"><h3>AI临床辅助入口</h3><div class="vct3-alert">AI只能提供病例摘要、鉴别诊断和检查建议；最终诊断、处方和医疗文书必须由执业兽医独立判断并确认。</div><button class="vct3-btn" id="v3ai">调用当前病例AI复核</button></div>`;[['v3primary','primary'],['v3certainty','certainty'],['v3basis','basis']].forEach(([id,k])=>$(id).onchange=e=>{d[k]=e.target.value;save(x)});$('#v3ddx').onchange=e=>{d.differentials=e.target.value.split(/\n+/).map(s=>s.trim()).filter(Boolean);m.ddx=d.differentials.join('\n');save(x)};$('#v3secondary').onchange=e=>{d.secondary=e.target.value.split(/\n+/).map(s=>s.trim()).filter(Boolean);save(x)};$('#v3ai').onclick=()=>{try{localStorage.setItem('VCT_AI_CASE_CONTEXT',JSON.stringify({encounterId:x.id,patient:p,customer:c,medical:m,generatedAt:now()}));alert('已建立当前病例 AI 上下文。请进入 AI 临床模块执行分析。')}catch{}};return}
 if(t==='treatment'){const p=m.planStructured;c.innerHTML=`<div class="vct3-card"><h3>治疗 / 处置计划</h3><div class="vct3-grid2">${[['goals','治疗目标'],['treatment','治疗方案'],['monitoring','监测指标 / 复查'],['nursing','护理方案'],['clientInstructions','主人沟通 / 居家执行'],['prognosis','预后'],['restrictions','活动 / 饮食限制']].map(([k,l])=>`<div class="vct3-field"><label>${l}</label><textarea data-plan="${k}">${esc(p[k])}</textarea></div>`).join('')}</div></div><div class="vct3-card"><h3>治疗安全核查</h3><div class="vct3-checks">${['身份/体重已核实','过敏/既往用药已核实','关键检验结果已查看','药物剂量已按体重核对','禁忌/相互作用已评估','主人已获知主要风险'].map((q,i)=>`<label><input type="checkbox" data-plancheck="${i}"> ${q}</label>`).join('')}</div></div>`;$$('[data-plan]').forEach(q=>q.onchange=()=>{p[q.dataset.plan]=q.value;m.plan=p;save(x)});return}
 if(t==='rx'){const rx=x.prescription||[];const orders=m.doctorOrders;c.innerHTML=`<div class="vct3-card"><h3>处方 / 医嘱工作区</h3><div class="vct3-alert">处方开具、处方审核、发药、收费是不同环节。锁定处方后再进入药房执行；特殊药品按适用规则单独处理。</div><table class="vct3-table"><thead><tr><th>药品</th><th>规格</th><th>数量</th><th>途径</th><th>剂量 / 用法</th></tr></thead><tbody>${rx.map(q=>`<tr><td>${esc(q.name||q.generic_name||'')}</td><td>${esc(q.spec||'')}</td><td>${esc(q.qty||q.quantity||'')}</td><td>${esc(q.route||'')}</td><td>${esc(q.dose||q.usage||'')}</td></tr>`).join('')||'<tr><td colspan="5">当前就诊尚未建立处方。可使用右侧原药房/处方模块。</td></tr>'}</tbody></table><div class="vct3-actions" style="margin-top:8px"><button class="vct3-btn primary" id="v3openrx">打开处方 / 药房</button><button class="vct3-btn" id="v3rxcheck">执行用药审核</button></div></div><div class="vct3-card"><h3>医生医嘱</h3><div class="vct3-grid2"><div class="vct3-field"><label>新增医嘱</label><textarea id="v3ordertext" placeholder="给药、护理、监测、禁食、活动限制等"></textarea></div><div><button class="vct3-btn primary" id="v3addorder">添加医嘱</button></div></div><table class="vct3-table"><thead><tr><th>时间</th><th>医嘱</th><th>状态</th></tr></thead><tbody>${orders.map(q=>`<tr><td>${esc(q.time?.slice(0,16)||'')}</td><td>${esc(q.text)}</td><td>${esc(q.status||'有效')}</td></tr>`).join('')||'<tr><td colspan="3">暂无医嘱</td></tr>'}</tbody></table></div>`;$('#v3openrx').onclick=()=>window.VCT_HIS_PRO?.show?.('pharmacy');$('#v3rxcheck').onclick=()=>{localStorage.setItem('VCT_AI_CASE_CONTEXT',JSON.stringify({encounterId:x.id,patient:p,medical:m,task:'药物安全审核',generatedAt:now()}));alert('已将当前病例和处方写入 AI 临床上下文。请执行药物审核。')};$('#v3addorder').onclick=()=>{const v=$('#v3ordertext').value.trim();if(v){orders.push({id:'O'+Date.now(),time:now(),text:v,status:'有效'});save(x);renderTab(t,x,m)}};return}
 if(t==='nursing'){const ns=m.nursingOrders,notes=m.progressNotes;c.innerHTML=`<div class="vct3-card"><h3>护理 / 执行任务</h3><div class="vct3-grid2"><div class="vct3-field"><label>新增护理任务</label><input id="v3nursing" placeholder="输液、生命体征、疼痛、饮食、尿量等"></div><div><button class="vct3-btn primary" id="v3addnursing">添加</button></div></div><table class="vct3-table"><thead><tr><th>时间</th><th>任务</th><th>状态</th></tr></thead><tbody>${ns.map((q,i)=>`<tr><td>${esc(q.time?.slice(0,16)||'')}</td><td>${esc(q.text)}</td><td><select data-ns="${i}"><option ${q.status==='待执行'?'selected':''}>待执行</option><option ${q.status==='执行中'?'selected':''}>执行中</option><option ${q.status==='已完成'?'selected':''}>已完成</option></select></td></tr>`).join('')||'<tr><td colspan="3">暂无护理任务</td></tr>'}</tbody></table></div><div class="vct3-card"><h3>病程记录</h3><div class="vct3-field"><label>新增病程记录</label><textarea id="v3note" placeholder="时间线 + 主观/客观变化 + 评估 + 下一步计划"></textarea></div><button class="vct3-btn primary" id="v3addnote">记录病程</button><div class="vct3-timeline" style="margin-top:10px">${notes.map(q=>`<div class="vct3-event"><time>${esc(q.time)}</time><b>${esc(q.author||'医生')}</b><div>${esc(q.text)}</div></div>`).join('')||'<span style="font-size:10px;color:#89969c">暂无病程记录</span>'}</div></div>`;$('#v3addnursing').onclick=()=>{const v=$('#v3nursing').value.trim();if(v){ns.push({id:'N'+Date.now(),time:now(),text:v,status:'待执行'});save(x);renderTab(t,x,m)}};$$('[data-ns]').forEach(q=>q.onchange=()=>{ns[+q.dataset.ns].status=q.value;save(x)});$('#v3addnote').onclick=()=>{const v=$('#v3note').value.trim();if(v){notes.unshift({id:'PN'+Date.now(),time:now(),author:read('VCT_HIS_ROLE','doctor'),text:v});save(x);renderTab(t,x,m)}};return}
 if(t==='followup'){const f=m.followupPlan;c.innerHTML=`<div class="vct3-card"><h3>复诊 / 回访计划</h3><div class="vct3-grid">${[['date','计划日期'],['channel','渠道'],['purpose','目的']].map(([k,l])=>`<div class="vct3-field"><label>${l}</label>${k==='channel'?`<select data-fu="channel"><option>电话</option><option>微信</option><option>短信</option><option>复诊到院</option></select>`:`<input data-fu="${k}" value="${esc(f[k]||'')}">`}</div>`).join('')}</div><div class="vct3-grid2" style="margin-top:7px"><div class="vct3-field"><label>主人需要观察的红旗信号</label><textarea data-fu="redFlags">${esc(f.redFlags||'')}</textarea></div><div class="vct3-field"><label>回访结果</label><textarea data-fu="result">${esc(f.result||'')}</textarea></div></div><button class="vct3-btn primary" id="v3savefu">保存回访计划</button></div>`;$$('[data-fu]').forEach(q=>{q.value=f[q.dataset.fu]||'';q.onchange=()=>{f[q.dataset.fu]=q.value;save(x)}});$('#v3savefu').onclick=()=>{f.status='待跟进';save(x);audit('FOLLOWUP_PLAN',{id:x.id,date:f.date});window.toast?toast('回访计划已保存'):alert('回访计划已保存')};return}
 }
 function renderState(x,m){const s=[['挂号',true],['病史',!!(m.history||x.registration?.chief)],['体检',!!m.examStructured?.temperature||!!m.exam],['检查',m.diagnosticOrders.length>0],['诊断',!!m.diagnosisStructured.primary],['治疗',!!m.planStructured.treatment],['处方',!!(x.prescription||[]).length],['医嘱',m.doctorOrders.length>0],['病程',m.progressNotes.length>0],['随访',!!m.followupPlan.date]];$('#v3state').innerHTML=s.map(q=>`<div style="padding:4px 0"><span style="display:inline-block;width:16px">${q[1]?'✓':'○'}</span>${q[0]}</div>`).join('')}
 function renderTimeline(x,m){const a=[];a.push({time:x.createdAt||x.registration?.time||now(),title:'建立就诊',text:x.registration?.visitType||'门诊'});if(m.diagnosticOrders.length)m.diagnosticOrders.forEach(q=>a.push({time:q.time,title:'检查：'+q.name,text:q.status+(q.result?' · '+q.result:'')}));if(m.progressNotes.length)m.progressNotes.forEach(q=>a.push({time:q.time,title:'病程记录',text:q.text}));if(m.followupPlan.date)a.push({time:m.followupPlan.date,title:'计划回访',text:m.followupPlan.purpose||''});a.sort((a,b)=>String(b.time).localeCompare(String(a.time)));$('#v3timeline').innerHTML=a.slice(0,15).map(q=>`<div class="vct3-event"><time>${esc(q.time)}</time><b>${esc(q.title)}</b><div>${esc(q.text)}</div></div>`).join('')}
 function finalize(x){const m=ensure(x);if(!m.diagnosisStructured.primary&&!m.assessment){alert('请先完成主要诊断/评估。');return}if(!confirm('确认完成本次接诊？完成后医疗记录原则上进入锁定状态；后续更正应保留版本/审计痕迹。'))return;m.finalStatus='FINAL';m.finalizedAt=now();m.finalizedBy=read('VCT_HIS_ROLE','doctor');x.queue=x.queue||{};x.queue.status='已完成';save(x);audit('FINALIZE_CASE_WORKSPACE',{id:x.id});render();alert('本次病例已完成。')}
 function boot(){let last='';setInterval(()=>{const page=localStorage.getItem('VCT_HIS_PRO_PAGE')||'';const x=current();if(page==='encounter'&&x){const body=$('#hisproBody');if(body&&!body.dataset.vct3){render();last=x.id}else if(body&&last!==x.id){render();last=x.id}}},250)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
