/* VCT Hospital OS 5.0-r08 — Stage 4 Clinical Encounter Engine */
(function(){'use strict';
const K='VCT_CLINICAL_EVENTS_V1';const $=(s,r=document)=>r.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,d)=>{try{const x=JSON.parse(localStorage.getItem(k));return x==null?d:x}catch{return d}};const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const now=()=>new Date().toISOString();
const role=()=>read('VCT_HIS_ROLE','doctor');const events=()=>read(K,[]);const current=()=>{const a=read('VCT_OUTPATIENT_FLOW20_V1',[]),id=localStorage.getItem('VCT_ACTIVE_ENCOUNTER_V1');return a.find(x=>x.id===id)||null};
function audit(action,meta){const a=read('VCT_HIS_PRO_AUDIT_V1',[]);a.unshift({time:now(),actor:role(),action,meta});write('VCT_HIS_PRO_AUDIT_V1',a.slice(0,5000))}
function emit(type,payload={},opts={}){const x=current();if(!x)return null;const e={eventId:'EV'+Date.now()+Math.random().toString(36).slice(2,7),encounterId:x.id,patientId:x.pet?.id||x.pet?.petId||'',eventTime:now(),operator:read('VCT_HIS_USER',''),role:role(),eventType:type,status:opts.status||'已保存',source:opts.source||'clinical-workspace',payload,relatedEventIds:opts.relatedEventIds||[],relatedObjectIds:opts.relatedObjectIds||[],version:1};const a=events();a.unshift(e);write(K,a.slice(0,20000));audit('CLINICAL_EVENT',{eventId:e.eventId,eventType:type,status:e.status,encounterId:x.id});return e}
function forCurrent(){const x=current();return x?events().filter(e=>e.encounterId===x.id):[]}
function label(t){return ({REGISTRATION:'挂号',TRIAGE:'分诊',HISTORY:'病史',PHYSICAL_EXAM:'体格检查',LAB_ORDER:'检验申请',LAB_RESULT:'检验结果',LAB_REVIEW:'检验审核',IMAGING_ORDER:'影像申请',IMAGING_RESULT:'影像报告',IMAGING_REVIEW:'影像解读',DIAGNOSIS:'诊断',TREATMENT:'治疗/处置',PRESCRIPTION:'处方开立',RX_REVIEW:'处方审核',DISPENSE:'发药',MEDICATION_ADMIN:'用药执行',DOCTOR_ORDER:'医嘱开立',ORDER_EXECUTE:'医嘱执行',NURSING_ORDER:'护理开立',NURSING_EXECUTE:'护理执行',INFUSION_ORDER:'输液开立',INFUSION_EXECUTE:'输液执行',PROCEDURE:'操作/手术',ANESTHESIA:'麻醉',PROGRESS_NOTE:'病程记录',CONSENT:'知情同意',BILLING:'收费',FOLLOWUP:'回访',DISCHARGE:'出院',FINALIZE:'病例归档'})[t]||t}
function install(){if($('#vct4Style'))return;const s=document.createElement('style');s.id='vct4Style';s.textContent='.vct4{margin-top:8px}.vct4bar{display:flex;gap:5px;align-items:center;flex-wrap:wrap;padding:7px;background:#fff;border:1px solid #d9e2e6;border-radius:8px}.vct4bar select,.vct4bar input{border:1px solid #ccd7dc;border-radius:6px;padding:6px;font-size:10px}.vct4btn{border:1px solid #d3dee2;background:#fff;border-radius:6px;padding:6px 9px;font-size:10px;cursor:pointer}.vct4btn.on{background:#e9f6f3;color:#0f766e;font-weight:700}.vct4timeline{margin-top:7px;background:#fff;border:1px solid #d9e2e6;border-radius:8px;padding:10px}.vct4ev{border-left:2px solid #dbe5e7;margin:0 0 9px 5px;padding-left:10px;position:relative}.vct4ev:before{content:"";position:absolute;left:-6px;top:4px;width:8px;height:8px;border-radius:50%;background:#0f766e}.vct4ev b{font-size:10px}.vct4ev small{display:block;color:#89969c;font-size:9px}.vct4ev p{margin:3px 0;font-size:10px;color:#59676e;white-space:pre-wrap}.vct4task{display:flex;justify-content:space-between;gap:8px;border:1px solid #e2e8eb;border-radius:6px;padding:6px;margin:4px 0;font-size:10px}.vct4muted{color:#89969c;font-size:10px}';document.head.appendChild(s)}
function render(){install();const body=$('#hisproBody');const x=current();if(!body||!x)return;let host=$('#vct4');if(!host){host=document.createElement('div');host.id='vct4';body.appendChild(host)}const es=forCurrent();const types=['ALL',...new Set(es.map(e=>e.eventType))];host.innerHTML='<div class="vct4bar"><b style="font-size:11px">临床事件引擎</b><select id="v4type">'+types.map(t=>`<option value="${esc(t)}">${t==='ALL'?'全部事件':esc(label(t))}</option>`).join('')+'</select><input id="v4search" placeholder="搜索事件内容 / 操作者"><button class="vct4btn on" id="v4timeline">病例时间轴</button><button class="vct4btn" id="v4tasks">临床待办</button><button class="vct4btn" id="v4emit">记录临床事件</button></div><div id="v4view"></div>';const draw=()=>{const q=$('#v4search').value.trim().toLowerCase(),t=$('#v4type').value;const arr=forCurrent().filter(e=>(t==='ALL'||e.eventType===t)&&(!q||JSON.stringify(e).toLowerCase().includes(q)));$('#v4view').innerHTML='<div class="vct4timeline">'+(arr.length?arr.map(e=>`<div class="vct4ev"><b>${esc(label(e.eventType))} · ${esc(e.status)}</b><small>${esc(e.eventTime)} · ${esc(e.role||'')} ${esc(e.operator||'')}</small><p>${esc(JSON.stringify(e.payload||{},null,2))}</p><button class="vct4btn" data-eid="${e.eventId}">查看事件</button></div>`).join(''):'<div class="vct4muted">当前就诊尚无临床事件。首次打开时可由系统初始化挂号事件。</div>')+'</div>';};
const tasks=()=>{const pending=forCurrent().filter(e=>['待结果','待审核','待执行','草稿'].includes(e.status));$('#v4view').innerHTML='<div class="vct4timeline"><b style="font-size:11px">待处理临床任务</b>'+(pending.length?pending.map(e=>`<div class="vct4task"><span>${esc(label(e.eventType))}<br><span class="vct4muted">${esc(e.eventTime)}</span></span><button class="vct4btn" data-task="${e.eventId}">处理</button></div>`).join(''):'<div class="vct4muted" style="margin-top:7px">暂无结构化待办。</div>')+'</div>';};
$('#v4timeline').onclick=()=>{draw();$('#v4timeline').classList.add('on');$('#v4tasks').classList.remove('on')};$('#v4tasks').onclick=()=>{tasks();$('#v4tasks').classList.add('on');$('#v4timeline').classList.remove('on')};$('#v4type').onchange=draw;$('#v4search').oninput=draw;$('#v4emit').onclick=()=>{const type=prompt('事件类型（如 PROGRESS_NOTE / LAB_REVIEW / ORDER_EXECUTE）：','PROGRESS_NOTE');if(!type)return;const text=prompt('事件内容：','');if(text==null)return;emit(type,{text},{status:'已保存'});draw()};if(!es.length)emit('REGISTRATION',{visitType:x.registration?.visitType||'门诊',mrn:x.mrn||''},{status:'已完成'});draw()}
function hook(){const x=current();if(!x)return;const m=x.medical||{};const es=forCurrent();if(!es.some(e=>e.eventType==='HISTORY')&&(m.history||x.registration?.chief))emit('HISTORY',{chief:x.registration?.chief||'',history:m.history||''});if(!es.some(e=>e.eventType==='PHYSICAL_EXAM')&&(m.examStructured&&Object.values(m.examStructured).some(Boolean)))emit('PHYSICAL_EXAM',m.examStructured);if(!es.some(e=>e.eventType==='DIAGNOSIS')&&m.diagnosisStructured?.primary)emit('DIAGNOSIS',m.diagnosisStructured,{status:'已确认'});}
let last='';setInterval(()=>{const page=localStorage.getItem('VCT_HIS_PRO_PAGE')||'',x=current();if(page==='encounter'&&x){if(last!==x.id){last=x.id;setTimeout(render,50)}hook();}},500);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,300));else setTimeout(render,300);
window.VCT_ENCOUNTER_ENGINE={emit,events:forCurrent,render};
})();
