/* VCT Hospital OS 5.0-r08 — Stage 2 Clinical Workbench
 * Mature HIS-aligned workflow layer. Inspired by common veterinary HIS architecture concepts;
 * no third-party code, branding, assets, or proprietary UI copied.
 */
(function(){'use strict';
 const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const read=(k,d)=>{try{const x=JSON.parse(localStorage.getItem(k));return x==null?d:x}catch{return d}};
 const flow=()=>read('VCT_OUTPATIENT_FLOW20_V1',[]);
 const active=()=>{const id=localStorage.getItem('VCT_ACTIVE_ENCOUNTER_V1');return flow().find(x=>x.id===id)||null};
 const patient=()=>{const x=active(); if(!x)return null; return {x,p:x.pet||{},c:x.customer||{},m:x.medical||{}}};
 const show=p=>window.VCT_HIS_PRO?.show?.(p);
 function install(){
   if($('#vctStage2Style'))return;
   const s=document.createElement('style');s.id='vctStage2Style';s.textContent=`
   .vct2-opbar{display:flex;gap:4px;overflow:auto;background:#fff;border:1px solid #d8e0e5;border-radius:9px;padding:4px;margin:0 0 10px}
   .vct2-opbar button{border:0;background:transparent;white-space:nowrap;border-radius:6px;padding:7px 10px;font-size:11px;color:#56656d;cursor:pointer}.vct2-opbar button:hover,.vct2-opbar button.active{background:#eef7f5;color:#0f766e;font-weight:800}
   .vct2-layout{display:grid;grid-template-columns:minmax(0,1fr) 265px;gap:10px;align-items:start}.vct2-main{min-width:0}.vct2-rail{position:sticky;top:10px;min-width:0}
   .vct2-card{background:#fff;border:1px solid #d8e0e5;border-radius:10px;padding:11px;margin-bottom:10px}.vct2-card h3{font-size:13px;margin:0 0 8px}.vct2-muted{font-size:10px;color:#87949b}.vct2-kv{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.vct2-kv>div{background:#f8fafb;border:1px solid #e5eaed;border-radius:7px;padding:7px}.vct2-kv small{display:block;color:#8a969c;margin-bottom:2px}.vct2-patient-name{font-size:18px;font-weight:800}.vct2-tags{display:flex;flex-wrap:wrap;gap:4px;margin-top:6px}.vct2-tag{font-size:10px;padding:3px 6px;border-radius:999px;background:#eef2f4}.vct2-risk{background:#fff6e8;color:#82570b}.vct2-action{width:100%;text-align:left;border:1px solid #d8e1e5;background:#fff;border-radius:7px;padding:7px 8px;margin:3px 0;font-size:11px;cursor:pointer}.vct2-action:hover{background:#f5f9f9}.vct2-action.primary{background:#0f766e;color:#fff;border-color:#0f766e}
   .vct2-clinical-tabs{display:flex;gap:2px;overflow:auto;border-bottom:1px solid #d8e0e5;margin:-2px 0 10px}.vct2-clinical-tabs button{border:0;background:transparent;padding:8px 11px;white-space:nowrap;font-size:11px;cursor:pointer;color:#596870}.vct2-clinical-tabs button.active{color:#0f766e;border-bottom:2px solid #0f766e;font-weight:800}
   .vct2-section-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.vct2-section{border:1px solid #e0e6e9;border-radius:8px;padding:8px;background:#fff}.vct2-section b{font-size:11px}.vct2-section textarea{width:100%;box-sizing:border-box;min-height:76px;margin-top:6px;border:1px solid #d3dce0;border-radius:6px;padding:7px;font-size:11px;resize:vertical}.vct2-section.full{grid-column:1/-1}
   .vct2-statusline{display:flex;gap:5px;flex-wrap:wrap;margin-bottom:9px}.vct2-status{font-size:10px;padding:4px 7px;border-radius:999px;background:#eef2f4;color:#65737a}.vct2-status.done{background:#eaf6ed;color:#39704b}.vct2-status.current{background:#e8f6f3;color:#0f766e;font-weight:800}
   .vct2-footer{position:sticky;bottom:0;background:rgba(255,255,255,.96);border-top:1px solid #d8e0e5;padding:7px;display:flex;gap:6px;justify-content:flex-end;z-index:5}.vct2-footer button{border:1px solid #d4dee2;background:#fff;border-radius:7px;padding:7px 10px;font-size:11px}.vct2-footer .primary{background:#0f766e;color:#fff;border-color:#0f766e}
   .vct2-workcards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.vct2-workcard{background:#fff;border:1px solid #d8e0e5;border-radius:9px;padding:10px;cursor:pointer}.vct2-workcard b{display:block;font-size:12px}.vct2-workcard span{font-size:10px;color:#87949b}
   @media(max-width:1050px){.vct2-layout{grid-template-columns:1fr}.vct2-rail{position:static}.vct2-workcards{grid-template-columns:repeat(2,minmax(0,1fr))}}
   @media(max-width:650px){.vct2-section-grid{grid-template-columns:1fr}.vct2-workcards{grid-template-columns:1fr}}
   `;document.head.appendChild(s);
 }
 function patientRail(){const el=$('#vct2Rail');if(!el)return;const z=patient();if(!z){el.innerHTML='<div class="vct2-card"><h3>患者上下文</h3><div class="vct2-muted">尚未选择当前患者。请从挂号/队列进入。</div><button class="vct2-action primary" data-v2="patients">打开患者中心</button></div>';return}
   const {x,p,c}=z; const risk=[p.allergy?'过敏：'+p.allergy:'',...(x.flags||[])].filter(Boolean);
   el.innerHTML=`<div class="vct2-card"><div class="vct2-patient-name">${esc(p.name||'患者')}</div><div class="vct2-muted">${esc(p.species||'')} · ${esc(p.breed||'')} · ${esc(p.sex||'')} · ${esc(p.age||'')}</div><div class="vct2-tags"><span class="vct2-tag">${esc(x.mrn||'')}</span><span class="vct2-tag">${esc(p.weight||'')} kg</span><span class="vct2-tag">${esc(x.queue?.status||'')}</span></div>${risk.length?`<div class="vct2-tags">${risk.map(r=>`<span class="vct2-tag vct2-risk">⚠ ${esc(r)}</span>`).join('')}</div>`:''}</div>
   <div class="vct2-card"><h3>患者快速操作</h3><button class="vct2-action primary" data-v2="encounter">当前接诊</button><button class="vct2-action" data-v2="patients">患者主档</button><button class="vct2-action" data-v2="docs">医疗文书</button><button class="vct2-action" data-v2="consent">知情同意</button><button class="vct2-action" data-v2="pharmacy">处方 / 药房</button><button class="vct2-action" data-v2="billing">收费结算</button><button class="vct2-action" data-v2="follow">复诊 / 回访</button></div>
   <div class="vct2-card"><h3>本次就诊</h3><div class="vct2-kv"><div><small>类型</small>${esc(x.registration?.visitType||'')}</div><div><small>医生</small>${esc(x.queue?.vet||'未分配')}</div><div><small>主诉</small>${esc(x.registration?.chief||'未填写')}</div><div><small>状态</small>${esc(x.queue?.status||x.status||'')}</div></div></div>`;
   $$('[data-v2]',el).forEach(b=>b.onclick=()=>show(b.dataset.v2));
 }
 function opbar(){const host=$('#vctBody');if(!host||$('#vct2Opbar'))return;const bar=document.createElement('div');bar.id='vct2Opbar';bar.className='vct2-opbar';bar.innerHTML=[['dash','工作台'],['queue','预约 / 挂号'],['queue','分诊 / 候诊'],['encounter','接诊'],['inpatient','住院 / ICU'],['billing','待收费'],['pharmacy','待发药'],['follow','待回访']].map(([p,l],i)=>`<button data-v2op="${p}" class="${i===0?'active':''}">${l}</button>`).join('');host.parentElement.insertBefore(bar,host);$$('[data-v2op]',bar).forEach(b=>b.onclick=()=>{show(b.dataset.v2op);setTimeout(sync,30)});}
 function wrapEncounter(){const body=$('#hisproBody');if(!body||body.dataset.vct2Wrapped==='1')return;const z=patient();if(!z)return;body.dataset.vct2Wrapped='1';
   const existing=[...body.children];const layout=document.createElement('div');layout.className='vct2-layout';const main=document.createElement('div');main.className='vct2-main';const rail=document.createElement('aside');rail.id='vct2Rail';rail.className='vct2-rail';
   const tabs=document.createElement('div');tabs.className='vct2-clinical-tabs';tabs.innerHTML=[['encounter','病历'],['docs','检验 / 影像 / 文书'],['pharmacy','处方 / 药房'],['consent','知情同意'],['surgery','手术 / 麻醉'],['inpatient','住院 / ICU'],['billing','收费'],['follow','随访']].map(([p,l],i)=>`<button data-v2ct="${p}" class="${i===0?'active':''}">${l}</button>`).join('');main.appendChild(tabs);
   const zstate=document.createElement('div');zstate.className='vct2-statusline';const x=z.x,m=z.m;const steps=[['挂号',true],['病史',!!(x.registration?.chief||m.history||m.past)],['体检',!!m.exam],['检查',!!(m.tests||m.results||x.labs?.length||x.imaging?.length)],['诊断',!!(m.dx||m.assessment)],['治疗',!!m.plan],['处方',!!x.prescription?.length],['文书',!!x.consents?.length],['随访',!!m.follow]];zstate.innerHTML=steps.map(([n,d])=>`<span class="vct2-status ${d?'done':''} ${!d&&n==='诊断'?'current':''}">${d?'✓':'○'} ${n}</span>`).join('');main.appendChild(zstate);
   const grid=document.createElement('div');grid.className='vct2-section-grid';const fields=[['现病史','history'],['既往史 / 用药史','past'],['疫苗 / 驱虫史','prevent'],['体格检查','exam'],['检查项目','tests'],['检查结果','results'],['诊断','dx'],['鉴别诊断','ddx'],['Assessment / 预后','assessment'],['治疗方案','plan'],['医嘱 / 监测','advice'],['复诊计划','follow'],['知情沟通','disclosure']];
   fields.forEach(([label,key],i)=>{const d=document.createElement('div');d.className='vct2-section '+(key==='exam'||key==='results'||key==='dx'||key==='plan'?'full':'');d.innerHTML=`<b>${label}</b><textarea data-v2field="${key}">${esc(m[key]||'')}</textarea>`;grid.appendChild(d)});main.appendChild(grid);
   const actions=document.createElement('div');actions.className='vct2-footer';actions.innerHTML='<button id="vct2Draft">保存草稿</button><button id="vct2AI">AI病例复核</button><button id="vct2Finalize" class="primary">完成接诊 / 锁定</button>';main.appendChild(actions);
   existing.forEach(n=>{if(n.classList?.contains('vct2-statusline'))return;});
   // Keep the original mature HIS form below as a detailed fallback/legacy editor, collapsed by default.
   const legacy=document.createElement('details');legacy.className='vct2-card';legacy.open=false;legacy.innerHTML='<summary style="cursor:pointer;font-size:12px;font-weight:800">详细医疗记录原始表单（兼容模式）</summary><div id="vct2Legacy"></div>';const holder=legacy.querySelector('#vct2Legacy');existing.forEach(n=>holder.appendChild(n));main.appendChild(legacy);
   layout.appendChild(main);layout.appendChild(rail);body.replaceChildren(layout);patientRail();
   $$('[data-v2ct]',tabs).forEach(b=>b.onclick=()=>show(b.dataset.v2ct));
   $('#vct2Draft').onclick=()=>saveDraft(z.x,grid,false);$('#vct2AI').onclick=()=>{try{window.VCT_HIS_PRO?.show?.('encounter');setTimeout(()=>window.alert('已将当前患者作为 AI 临床复核上下文；AI建议仍需执业兽医独立判断。'),30)}catch{}};
   $('#vct2Finalize').onclick=()=>saveDraft(z.x,grid,true);
 }
 function saveDraft(x,grid,finalize){const m=x.medical=x.medical||{};$$('[data-v2field]',grid).forEach(t=>m[t.dataset.v2field]=t.value);m.updatedAt=new Date().toISOString();x.updatedAt=m.updatedAt;localStorage.setItem('VCT_OUTPATIENT_FLOW20_V1',JSON.stringify(flow()));if(finalize){if(!m.dx&&!m.assessment){alert('请至少完成诊断/评估后再完成接诊。');return}m.finalStatus='FINAL';m.finalizedAt=m.updatedAt;m.finalizedBy=read('VCT_HIS_ROLE','doctor');x.queue=x.queue||{};x.queue.status='已完成';localStorage.setItem('VCT_ACTIVE_ENCOUNTER_V1',x.id);alert('本次接诊已完成并锁定。后续更正应形成版本并保留审计痕迹。')}else alert('接诊草稿已保存。');sync();}
 function dashEnhance(){const body=$('#hisproBody');if(!body||body.dataset.vct2Dash==='1')return;body.dataset.vct2Dash='1';const a=flow(),today=new Date().toISOString().slice(0,10),td=a.filter(x=>(x.createdAt||'').slice(0,10)===today);const box=document.createElement('div');box.className='vct2-workcards';box.innerHTML=[['预约 / 挂号','进入今日接诊入口','queue'],['候诊 / 分诊',`${td.filter(x=>['候诊','已叫号'].includes(x.queue?.status)).length} 个待处理`,'queue'],['医生接诊',`${td.filter(x=>x.queue?.status==='接诊中').length} 个进行中`,'encounter'],['药房 / 收费','查看待发药与待收费','pharmacy']].map(([t,s,p])=>`<div class="vct2-workcard" data-v2dash="${p}"><b>${t}</b><span>${s}</span></div>`).join('');body.prepend(box);$$('[data-v2dash]',box).forEach(b=>b.onclick=()=>show(b.dataset.v2dash));}
 function sync(){install();opbar();const page=localStorage.getItem('VCT_HIS_PRO_PAGE')||'dash';if(page==='encounter'){wrapEncounter()}else if(page==='dash'){dashEnhance()}else{const b=$('#hisproBody');if(b){b.dataset.vct2Wrapped='';b.dataset.vct2Dash=''}}patientRail();}
 function boot(){let n=0;const timer=setInterval(()=>{n++;if($('#hisproBody')){sync();if(n>20)clearInterval(timer)}if(n>40)clearInterval(timer)},100);const obs=new MutationObserver(()=>{if($('#hisproBody'))sync()});obs.observe(document.body,{childList:true,subtree:true});setTimeout(()=>obs.disconnect(),30000);}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
