/* VCT Hospital OS 5.0-r08 — Mature HIS Shell / Patient & Encounter UX
 * Layout reference: mature veterinary HIS concepts (Shell, multi-level navigation,
 * patient context, work platform, encounter workspace). No third-party code/UI copied.
 */
(function(){'use strict';
function q(s,r=document){return r.querySelector(s)}
function qa(s,r=document){return [...r.querySelectorAll(s)]}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function read(k,d){try{const x=JSON.parse(localStorage.getItem(k));return x==null?d:x}catch{return d}}
function flow(){return read('VCT_OUTPATIENT_FLOW20_V1',[])}
function active(){const id=localStorage.getItem('VCT_ACTIVE_ENCOUNTER_V1');return flow().find(x=>x.id===id)||null}
function setActive(id){if(id)localStorage.setItem('VCT_ACTIVE_ENCOUNTER_V1',id)}
function go(page){window.VCT_HIS_PRO?.show?.(page)}
const tree={
 daily:{label:'日常工作',icon:'▦',children:{work:{label:'工作平台',items:[['dash','今日工作台'],['queue','候诊 / 分诊'],['queue','预约 / 挂号'],['patients','客户 / 患者']]},tasks:{label:'我的任务',items:[['queue','待接诊'],['billing','待收费'],['pharmacy','待发药'],['follow','待回访']]}}},
 medical:{label:'医疗中心',icon:'✚',children:{clinical:{label:'临床工作',items:[['encounter','接诊工作台'],['patients','患者中心'],['queue','门诊队列'],['inpatient','住院 / ICU']]},records:{label:'医疗记录',items:[['encounter','电子病历 / POMR'],['docs','医疗文书中心'],['consent','知情同意'],['surgery','手术 / 麻醉']]},diagnostics:{label:'辅助诊疗',items:[['encounter','临床推理 / AI'],['docs','检验 / 影像结果'],['pharmacy','处方 / 用药审核']]}}},
 pharmacy:{label:'药房与财务',icon:'▤',children:{pharm:{label:'药房',items:[['pharmacy','药品目录'],['pharmacy','库存管理'],['pharmacy','处方发药'],['pharmacy','近效期 / 低库存']]},finance:{label:'财务',items:[['billing','收费 / 结算'],['billing','收费项目'],['reports','经营收入']]},rx:{label:'处方',items:[['docs','处方打印'],['pharmacy','处方审方']]}}},
 customer:{label:'客户运营',icon:'♙',children:{crm:{label:'客户 / 患者',items:[['patients','患者中心'],['patients','客户档案']]},service:{label:'服务',items:[['queue','预约管理'],['follow','复诊 / 回访'],['billing','会员 / 储值']]}}},
 management:{label:'医院管理',icon:'⚙',children:{ops:{label:'运营管理',items:[['reports','经营统计'],['audit','审计 / 备份'],['settings','医院设置']]},clinical:{label:'医疗管理',items:[['reports','医疗质量'],['inpatient','住院运营'],['surgery','手术运营']]},system:{label:'系统',items:[['settings','角色 / 权限'],['audit','数据安全']]}}},
 ai:{label:'AI与智能',icon:'✦',children:{aiClinical:{label:'AI临床',items:[['encounter','病例智能助手'],['encounter','鉴别诊断 / 检查建议'],['encounter','用药审核']]},aiOps:{label:'AI经营',items:[['reports','经营分析'],['follow','智能回访'],['pharmacy','库存预警']]}}}
};
const pageLabel={dash:'今日工作台',queue:'候诊 / 挂号 / 分诊',patients:'患者中心',encounter:'接诊工作台',inpatient:'住院 / ICU',surgery:'手术 / 麻醉',billing:'收费 / 结算',pharmacy:'药房',follow:'复诊 / 回访',docs:'医疗文书中心',consent:'知情同意',reports:'统计 / 经营',audit:'审计 / 备份',settings:'医院设置'};
function installCss(){if(q('#vctMatureShellCss'))return;const s=document.createElement('style');s.id='vctMatureShellCss';s.textContent=`
#hispro.vct-mature{padding:0!important;background:#f3f6f8!important}
.vct-mature-shell{display:grid;grid-template-columns:248px minmax(0,1fr);min-height:calc(100vh - 126px);background:#f3f6f8}
.vct-mature-sidebar{background:#fff;border-right:1px solid #d8e0e5;display:flex;flex-direction:column;min-height:0;position:sticky;top:112px;height:calc(100vh - 124px);z-index:40}
.vct-mature-logo{padding:14px 16px 10px;border-bottom:1px solid #edf1f3}.vct-mature-logo b{font-size:16px}.vct-mature-logo span{display:block;font-size:11px;color:#8a98a1;margin-top:3px}
.vct-level1{display:flex;gap:3px;padding:8px;border-bottom:1px solid #e8edef;overflow-x:auto;flex:none}.vct-level1 button{border:0;background:#fff;border-radius:7px;padding:8px 10px;white-space:nowrap;font-size:12px;color:#53616a;cursor:pointer}.vct-level1 button.active{background:#e7f5f2;color:#0f766e;font-weight:800}
.vct-nav-search{padding:8px}.vct-nav-search input{width:100%;height:34px;box-sizing:border-box;border:1px solid #d5dee3;border-radius:7px;padding:7px 9px;background:#f8fafb}
.vct-level2{flex:1;overflow:auto;padding:3px 7px 12px}.vct-section{margin:5px 0 10px}.vct-section-title{display:flex;align-items:center;justify-content:space-between;padding:7px 9px;color:#7b8991;font-size:11px;font-weight:800;cursor:pointer;text-transform:none}.vct-section-title i{font-style:normal;color:#a0adb4}.vct-section-body{padding:0 2px}.vct-level3{width:100%;border:0;background:transparent;text-align:left;padding:8px 9px;border-radius:7px;color:#314048;font-size:12px;cursor:pointer;display:flex;align-items:center;gap:7px}.vct-level3:hover{background:#f1f6f7}.vct-level3.active{background:#e8f6f3;color:#0f766e;font-weight:800}.vct-level3:before{content:'›';color:#9aa7ad}.vct-nav-foot{border-top:1px solid #edf1f3;padding:9px 12px;font-size:10px;color:#94a3b8}
.vct-mature-main{min-width:0;padding:12px 14px 18px}.vct-breadcrumb{font-size:11px;color:#8b98a0;margin:0 0 6px 2px}.vct-workbar{background:#fff;border:1px solid #d8e0e5;border-radius:10px;display:flex;align-items:center;gap:8px;padding:7px 9px;margin-bottom:10px;min-width:0}.vct-workbar .vct-work-title{font-size:13px;font-weight:800;white-space:nowrap}.vct-workbar .vct-work-spacer{flex:1}.vct-workbar button{border:1px solid #dbe4e8;background:#fff;border-radius:7px;padding:7px 10px;font-size:11px;cursor:pointer}.vct-workbar button.primary{background:#0f766e;color:#fff;border-color:#0f766e}
.vct-context{background:#fff;border:1px solid #d8e0e5;border-radius:10px;padding:10px 12px;margin-bottom:10px;display:none}.vct-context.show{display:block}.vct-context-top{display:flex;align-items:center;gap:10px}.vct-avatar{width:38px;height:38px;border-radius:9px;background:#eef4f5;display:flex;align-items:center;justify-content:center;font-size:20px}.vct-context-main{min-width:0}.vct-context-main b{font-size:15px}.vct-context-main span{font-size:11px;color:#687780}.vct-context-meta{display:flex;flex-wrap:wrap;gap:5px;margin-top:5px}.vct-context-meta span{padding:3px 7px;border-radius:999px;background:#f2f5f6;font-size:10px;color:#5d6a71}.vct-context-alert{margin-left:auto;display:flex;gap:4px;flex-wrap:wrap;justify-content:flex-end}.vct-context-alert span{padding:4px 7px;border-radius:999px;background:#fff5e7;color:#8a5b0c;font-size:10px}
.vct-encounter-tabs{display:flex;gap:2px;background:#fff;border:1px solid #d8e0e5;border-radius:9px;padding:4px;margin-bottom:10px;overflow:auto}.vct-encounter-tabs button{border:0;background:transparent;padding:8px 10px;white-space:nowrap;border-radius:6px;font-size:11px;color:#596870;cursor:pointer}.vct-encounter-tabs button.active{background:#e8f6f3;color:#0f766e;font-weight:800}
.vct-taskline{display:flex;gap:5px;flex-wrap:wrap;margin-bottom:10px}.vct-taskline span{font-size:10px;padding:4px 7px;border-radius:999px;background:#eef2f4;color:#66747b}.vct-taskline span.done{background:#e9f6ed;color:#39704a}.vct-taskline span.current{background:#e8f6f3;color:#0f766e;font-weight:700}
.vct-patient-toolbar{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.vct-patient-toolbar button{border:1px solid #d8e1e5;background:#fff;border-radius:7px;padding:7px 10px;font-size:11px;cursor:pointer}.vct-patient-toolbar button.primary{background:#0f766e;color:#fff;border-color:#0f766e}
.vct-hidden{display:none!important}
@media(max-width:900px){.vct-mature-shell{grid-template-columns:1fr}.vct-mature-sidebar{position:static;height:auto}.vct-level1{overflow-x:auto}.vct-level2{max-height:270px}.vct-mature-main{padding:9px}.vct-context-top{align-items:flex-start}.vct-context-alert{margin-left:0}.vct-workbar{overflow:auto}}
`;document.head.appendChild(s)}
function buildShell(){const host=q('#hispro');if(!host)return;host.classList.add('vct-mature');host.innerHTML=`<div class="vct-mature-shell"><aside class="vct-mature-sidebar"><div class="vct-mature-logo"><b>VCT Hospital OS</b><span>5.0-r08 · Veterinary HIS</span></div><div class="vct-level1" id="vctLevel1"></div><div class="vct-nav-search"><input id="vctNavSearch" placeholder="搜索功能 / 模块…"></div><div class="vct-level2" id="vctLevel2"></div><div class="vct-nav-foot">医院工作台 · 多级业务导航 · 患者上下文</div></aside><section class="vct-mature-main"><div class="vct-breadcrumb" id="vctBreadcrumb">医院 / 日常工作 / 今日工作台</div><div class="vct-workbar"><span class="vct-work-title" id="vctWorkTitle">今日工作台</span><span class="vct-work-spacer"></span><button id="vctReturnClinical">临床工具箱</button><button id="vctCurrentPatient">当前患者</button><button class="primary" id="vctNewEncounter">＋ 新建接诊</button></div><div id="vctContext" class="vct-context"></div><div id="vctEncounterTabs" class="vct-encounter-tabs vct-hidden"></div><div id="vctTaskline" class="vct-taskline vct-hidden"></div><div id="vctPatientToolbar" class="vct-patient-toolbar vct-hidden"></div><div id="vctBody"><div id="hisproBody"></div><span id="hisproCrumb" class="vct-hidden"></span><span id="hisproTitle" class="vct-hidden"></span><button id="hisproNew" class="vct-hidden" type="button"></button></div></section></div>`;
 let top=localStorage.getItem('VCT_MATURE_TOP')||'daily';let page=localStorage.getItem('VCT_HIS_PRO_PAGE')||'dash';
 function renderL1(){const el=q('#vctLevel1');el.innerHTML=Object.entries(tree).map(([k,v])=>`<button data-top="${k}" class="${k===top?'active':''}">${v.icon} ${esc(v.label)}</button>`).join('');qa('[data-top]',el).forEach(b=>b.onclick=()=>{top=b.dataset.top;localStorage.setItem('VCT_MATURE_TOP',top);renderL1();renderL2();});}
 function renderL2(filter=''){const el=q('#vctLevel2');const g=tree[top];el.innerHTML=Object.entries(g.children).map(([k,v])=>`<div class="vct-section"><div class="vct-section-title" data-sec="${k}"><span>${esc(v.label)}</span><i>⌄</i></div><div class="vct-section-body">${v.items.map(([p,l])=>`<button class="vct-level3 ${p===page?'active':''}" data-page="${p}" data-label="${esc(l)}">${esc(l)}</button>`).join('')}</div></div>`).join('');
  if(filter){qa('.vct-section',el).forEach(sec=>{const ok=sec.innerText.toLowerCase().includes(filter.toLowerCase());sec.style.display=ok?'':'none'})}
  qa('[data-sec]',el).forEach(h=>h.onclick=()=>{const body=h.nextElementSibling;body.classList.toggle('vct-hidden');h.querySelector('i').textContent=body.classList.contains('vct-hidden')?'›':'⌄'});
  qa('[data-page]',el).forEach(b=>b.onclick=()=>{page=b.dataset.page;localStorage.setItem('VCT_HIS_PRO_PAGE',page);qa('[data-page]',el).forEach(x=>x.classList.toggle('active',x===b));updateChrome();go(page);setTimeout(enhancePage,0)});
 }
 function updateChrome(){const label=pageLabel[page]||page;const g=tree[top];q('#vctBreadcrumb').textContent=`医院 / ${g.label} / ${label}`;q('#vctWorkTitle').textContent=label;}
 q('#vctNavSearch').oninput=e=>renderL2(e.target.value.trim());
 q('#vctReturnClinical').onclick=()=>{document.body.classList.remove('vct-hospital-mode');const n=q('nav#nav');if(n)n.classList.remove('vct-nav-hidden');q('#hispro').style.display='none';window.alert('已返回临床工具箱')};
 q('#vctCurrentPatient').onclick=()=>{const x=active();if(x){go('encounter');setTimeout(enhancePage,0)}else go('patients')};
 q('#vctNewEncounter').onclick=()=>window.VCT_HIS_PRO?.newEncounterForm?.() || window.alert('新建接诊模块未加载');
 renderL1();renderL2();updateChrome();
 window.VCT_MATURE_NAV={setTop:k=>{if(tree[k]){top=k;localStorage.setItem('VCT_MATURE_TOP',k);renderL1();renderL2()}},go:p=>{page=p;localStorage.setItem('VCT_HIS_PRO_PAGE',p);updateChrome();go(p);setTimeout(enhancePage,0)}};
}
function context(){const x=active(),el=q('#vctContext');if(!el)return;if(!x){el.classList.remove('show');return}const p=x.pet||{},c=x.customer||{},m=x.medical||{};const flags=[p.allergy?'过敏：'+p.allergy:'',...(x.flags||[]).map(String)].filter(Boolean);el.classList.add('show');el.innerHTML=`<div class="vct-context-top"><div class="vct-avatar">${p.species==='猫'?'🐱':p.species==='犬'?'🐶':'🐾'}</div><div class="vct-context-main"><b>${esc(p.name||'患者')}</b> <span>${esc(p.species||'')} · ${esc(p.breed||'')} · ${esc(p.sex||'')} · ${esc(p.age||'')} · ${esc(p.weight||'')} kg</span><div class="vct-context-meta"><span>病历号 ${esc(x.mrn||'')}</span><span>主人 ${esc(c.name||'')}</span><span>本次 ${esc(x.registration?.visitType||'就诊')}</span><span>状态 ${esc(x.queue?.status||x.status||'')}</span></div></div><div class="vct-context-alert">${flags.length?flags.map(f=>`<span>⚠ ${esc(f)}</span>`).join(''):'<span>无已登记重点风险</span>'}</div></div>`}
function taskline(){const el=q('#vctTaskline'),x=active();if(!el)return;if(!x){el.classList.add('vct-hidden');return}const m=x.medical||{};const tasks=[['挂号',true],['病史',!!(x.registration?.chief||m.history)],['体检',!!m.exam],['检查',!!(m.tests||m.results||x.labs?.length||x.imaging?.length)],['诊断',!!(m.dx||m.assessment)],['治疗',!!m.plan],['处方',!!(x.prescription?.length)],['文书',!!(x.consents?.length)],['随访',!!(m.follow||x.followups?.length)]];el.classList.remove('vct-hidden');el.innerHTML=tasks.map(([n,d])=>`<span class="${d?'done':''} ${(!d&&n==='诊断')?'current':''}">${d?'✓':'○'} ${n}</span>`).join('')}
function enhancePatient(){const body=q('#hisproBody');if(!body)return;const tb=q('#vctPatientToolbar');tb.classList.remove('vct-hidden');tb.innerHTML=`<button class="primary" id="vctPtNew">＋ 新建接诊</button><button id="vctPtEncounter">进入当前接诊</button><button id="vctPtDocs">医疗文书</button><button id="vctPtBill">收费结算</button>`;q('#vctPtNew').onclick=()=>q('#vctNewEncounter')?.click();q('#vctPtEncounter').onclick=()=>go('encounter');q('#vctPtDocs').onclick=()=>go('docs');q('#vctPtBill').onclick=()=>go('billing');}
function enhanceEncounter(){const x=active();if(!x)return;const tabs=q('#vctEncounterTabs');tabs.classList.remove('vct-hidden');tabs.innerHTML=[['病历','encounter'],['患者中心','patients'],['检验 / 影像','docs'],['处方 / 药房','pharmacy'],['文书 / 同意','consent'],['收费','billing'],['随访','follow']].map(([l,p])=>`<button class="${p==='encounter'?'active':''}" data-et="${p}">${l}</button>`).join('');qa('[data-et]',tabs).forEach(b=>b.onclick=()=>go(b.dataset.et));}
function enhancePage(){const p=localStorage.getItem('VCT_HIS_PRO_PAGE')||'dash';context();taskline();q('#vctPatientToolbar')?.classList.add('vct-hidden');q('#vctEncounterTabs')?.classList.add('vct-hidden');if(p==='patients')enhancePatient();if(p==='encounter')enhanceEncounter();}
function boot(){installCss();const old=q('#hispro');if(!old)return;buildShell();document.body.classList.add('vct-hospital-mode');setTimeout(()=>{const p=localStorage.getItem('VCT_HIS_PRO_PAGE')||'dash';go(p);enhancePage()},20)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0));else setTimeout(boot,0);
})();
