/* VCT Hospital OS 5.0-r08 — Medical Record / Prescription / Consent Engine
 * Regulatory baseline: PRC Ministry of Agriculture and Rural Affairs Announcement No.734,
 * Animal Medical Record Management Specification; Veterinary Prescription Format and Application Specification;
 * Measures for Administration of Practicing Veterinarians and Rural Veterinarians; Animal Diagnosis and Treatment Institution Measures.
 * AI output is draft/advisory only. Final medical record and prescription require veterinarian review/confirmation/signature.
 */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const now=()=>new Date();
const iso=()=>{const d=now();const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`};
const uuid=()=>crypto?.randomUUID?.()||('vct-'+Date.now()+'-'+Math.random().toString(16).slice(2));
const get=v=>$(v)?.value?.trim()||'';
const set=(id,v)=>{if($(id))$(id).value=v??''};
const audit=(action,detail={})=>{
  const arr=JSON.parse(localStorage.getItem('VCT_MED_AUDIT')||'[]');
  arr.push({id:uuid(),time:iso(),action,detail});
  localStorage.setItem('VCT_MED_AUDIT',JSON.stringify(arr.slice(-2000)));
};

function ensureCaseExtras(){
 const caseView=$('case'); if(!caseView||$('vctMedicalPanel'))return;
 const card=document.createElement('div');card.className='card';card.id='vctMedicalPanel';
 card.innerHTML=`<h3>🏥 正式医疗文书中心 5.0-r08</h3>
 <div class="info">从当前病例自动带入患者、主人、就诊时间、体重、主诉、病史、检查、诊断、治疗和医嘱。AI内容仅作为草稿；医生确认后才能生成正式病历/处方。签名后的正式文书锁定并记录操作痕迹。</div>
 <div class="grid">
 <div><label>就诊日期/时间<input id="mrVisitTime" type="datetime-local"></label><label>就诊类型<select id="mrVisitType"><option>初诊</option><option>复诊</option><option>急诊</option><option>转诊</option></select></label><label>主诊执业兽医师<input id="mrVet" placeholder="执业兽医师姓名"></label><label>执业兽医师备案/签名标识<input id="mrVetSign" placeholder="签名留样/专用签章编号（按医院实际填写）"></label></div>
 <div><label>体格检查（结构化补充）<textarea id="mrExam" placeholder="T、HR、RR、SpO₂、BP、MM、CRT、精神、体况、脱水、心肺、腹部、泌尿、生殖、神经、肌骨、皮肤等"></textarea></label><label>诊疗意见/预后<textarea id="mrAssessment" placeholder="主要问题、支持证据、鉴别诊断、诊断结论、预后与不确定性"></textarea></label></div>
 <div><label>医嘱（正式病历）<textarea id="mrAdvice" placeholder="用药/护理/饮食/活动限制/监测/复诊/危险信号"></textarea></label><label>知情沟通摘要<textarea id="mrDisclosure" placeholder="已向宠主说明疾病、检查、治疗、替代方案、风险、预后、费用及拒绝/延误后果"></textarea></label></div>
 <div><label>医生确认<select id="mrConfirmed"><option value="no">未确认</option><option value="yes">我已核对并确认以上内容为本次亲自诊疗记录</option></select></label><label>电子签名/确认<input id="mrSignature" placeholder="输入医生姓名/专用签章标识"></label><button class="primary" id="mrFinalize">确认并锁定正式病历</button><div id="mrStatus"></div></div>
 </div>
 <hr><h4>处方</h4><div id="rxRows"></div><button class="secondary" id="rxAdd">＋增加药品</button>
 <div class="toolbar" style="margin-top:10px"><button class="primary" id="rxFinalize">医生确认并锁定处方</button><button class="secondary" id="printMedical">🖨 打印门/急诊病历</button><button class="secondary" id="printRx">🖨 打印兽医处方（A5）</button><button class="secondary" id="printFull">🖨 打印病历+处方</button></div>
 <div id="rxStatus"></div>
 <hr><h4>知情同意书</h4><div class="toolbar"><select id="consentType"></select><button class="primary" id="consentGenerate">生成并打印知情同意书</button></div>
 <div class="muted">模板按风险告知、替代方案、拒绝/延误后果、费用与预后不确定性、主人确认、医生签名、版本和时间设计。模板不能保证免除医院或兽医依法应承担的责任，应结合具体病例和当地监管/律师意见。</div>`;
 caseView.querySelector('.card').appendChild(card);
 const d=now();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());set('mrVisitTime',d.toISOString().slice(0,16));
 populateConsent();
 $('rxAdd').onclick=()=>addRxRow();
 $('mrFinalize').onclick=finalizeRecord;
 $('rxFinalize').onclick=finalizeRx;
 $('printMedical').onclick=()=>printDoc('medical');
 $('printRx').onclick=()=>printDoc('rx');
 $('printFull').onclick=()=>printDoc('full');
 $('consentGenerate').onclick=()=>printConsent(get('consentType'));
 addRxRow();
}

const CONSENTS={
 vaccine:{title:'动物疫苗接种知情同意书',risk:'疫苗接种总体安全，但可能发生注射部位疼痛、肿胀、短暂精神/食欲下降、发热、呕吐等；少数动物可能发生过敏反应，极少数发生严重过敏性休克或其他严重不良反应。免疫并非百分之百有效，也不能保证不感染、不发病或不传播病原体；母源抗体、免疫状态、疾病状态、疫苗保存/运输、接种程序、病原体变异等均可能影响效果。',items:['已核对动物身份、物种、年龄、性别及体重','已询问既往疫苗史、过敏史、免疫抑制疾病/用药及近期健康状态','已说明疫苗名称、生产企业/批号、有效期、接种途径、部位及程序（按实际产品填写）','已说明正常反应、异常反应和就医指征','已说明可能存在免疫失败及后续加强免疫需求','已说明如动物处于疾病潜伏期或已感染，疫苗不能替代诊断和治疗'],after:'接种后建议按医院要求留观；如出现面部/喉部肿胀、呼吸困难、反复呕吐、虚脱、意识异常等，应立即就医。'},
 anesthesia:{title:'麻醉知情同意书',risk:'麻醉具有个体差异和不可预测风险。可能发生低血压、低通气/呼吸暂停、低氧血症、低体温、心律失常、误吸、苏醒延迟、麻醉相关器官损伤、气道损伤、过敏反应，极少数可发生心肺骤停、严重并发症或死亡。风险受年龄、品种、基础疾病、ASA分级、脱水、贫血、电解质/酸碱异常、药物及手术类型等影响。',items:['已完成身份、体重、病史、过敏史和既往麻醉史核对','已说明拟采用麻醉方式、麻醉目的及预计过程','已说明术前检查的必要性及其局限性','已说明麻醉监测项目及可能根据病情追加监测/治疗','已说明麻醉风险、替代方案和延期/取消麻醉的可能性','已说明发生紧急情况时可能需要气道管理、机械通气、血管活性药物、输血、CPR等抢救措施'],after:'麻醉后可能出现嗜睡、步态不稳、恶心或食欲下降等。出院后应严格遵守禁食/饮水、保温、活动限制和用药要求；出现呼吸异常、持续呕吐、无法站立、意识异常或其他严重症状应立即联系医院。'},
 surgery:{title:'手术/侵入性操作知情同意书',risk:'任何手术均存在疼痛、出血、感染、组织损伤、麻醉风险、伤口问题、术后并发症、治疗失败、复发、再次手术及死亡风险。即使按照规范完成手术，也不能保证达到预期结果。复杂病例可能需要术中扩大操作范围或追加处置。',items:['已说明拟实施手术/操作的名称、目的、主要步骤和预计范围','已说明可能的替代治疗及不手术/延期的可能后果','已说明术中发现与术前判断不一致时可能需要调整方案','已说明可能涉及组织切除、病理送检、输血、引流、导尿等追加措施（按实际勾选）','已说明费用可能因追加检查/治疗/并发症而变化','已说明术后护理、复诊、拆线及可能并发症'],after:'术后应按医嘱限制活动、保护切口、按时用药和复诊。出现大量出血、切口裂开、持续呕吐、严重疼痛、呼吸困难、精神持续恶化等情况应立即就诊。'},
 euthanasia:{title:'动物安乐死知情同意书',risk:'安乐死的目的为在符合动物福利和临床适应证的情况下，以尽量减少恐惧、疼痛和痛苦的方式结束动物生命。实施后动物死亡不可逆。个体可能出现意识改变、肌肉抽动、排尿/排便、深呼吸样动作等临终现象，这些不一定代表动物仍有意识或感受疼痛，但可能对主人造成心理冲击。',items:['已确认动物身份及主人/有权处分人的授权','已充分说明疾病状态、预后及继续治疗/姑息治疗等替代方案','已说明安乐死不可逆及遗体后续处理选择','已说明实施过程中可能出现的生理反应','已说明如动物出现躁动、血管通路困难等情况，可能需要额外镇静或调整操作','已给予主人提问和考虑时间（急危重情况除外，按实际记录）'],after:'死亡确认由执业兽医师完成并记录时间。遗体处理方式应按主人选择及当地相关规定执行；涉及疑似传染病动物时应遵守疫情报告、隔离和无害化处理等要求。'},
 poisoning:{title:'动物中毒/疑似中毒诊疗知情同意书',risk:'中毒诊疗高度依赖毒物种类、剂量、摄入时间、吸收程度及器官损伤程度。部分毒物无特异性解毒剂，治疗可能只能支持生命并控制并发症。即使及时治疗，也可能发生肝肾损伤、凝血障碍、神经损伤、吸入性肺炎、心律失常、休克、癫痫、昏迷或死亡。部分处置（如催吐、洗胃等）在特定毒物或状态下可能有禁忌。',items:['已记录疑似毒物、成分/包装、摄入时间及估计剂量（如可获得）','已说明必要时需进行血液、尿液、影像或专项毒物检测，且检测存在时间窗和假阴/假阳性可能','已说明解毒治疗、胃肠去污、液体支持、抗惊厥、氧疗等措施及其风险','已说明部分毒物可能出现延迟性损伤，需要连续监测或住院','已说明预后取决于毒物、剂量、时间及器官损伤程度','已说明无法确定毒物时治疗方案存在不确定性'],after:'如发现摄入新的毒物/药物、症状突然加重、抽搐、呼吸困难、意识改变、出血或虚脱，应立即告知医院。未经兽医指导不要自行催吐或给予家庭解毒措施。'},
 hospitalization:{title:'住院诊疗知情同意书',risk:'住院期间存在疾病自然进展、院内交叉感染、应激、输液相关并发症、跌落/拔管、误吸、药物不良反应及病情突然恶化等风险。治疗方案可能随监测结果动态调整。',items:['已说明住院目的、预计观察项目和治疗计划','已说明可能追加检查、治疗和抢救措施','已说明住院费用及因病情变化产生额外费用的可能性','已说明探视、喂食、活动及陪护要求','已说明病情恶化时的联系及授权方式'],after:'医院将按记录进行病情监测，但医疗风险不能完全消除。'},
 infusion:{title:'输液/静脉治疗知情同意书',risk:'输液可能发生液体过负荷、低体温、电解质/酸碱异常、静脉炎、渗漏、血管损伤、感染、药物不良反应或过敏反应；心肾功能异常动物风险更高。',items:['已说明输液目的、液体类型、预计速度及监测方式','已说明根据尿量、体重、心肺状态等动态调整的必要性','已说明发生液体过负荷等情况时可能需要暂停或改变方案','已说明静脉通路维护和限制活动要求'],after:'发现呼吸加快/困难、明显肿胀、疼痛、输液部位异常等应立即告知医护人员。'},
 transfusion:{title:'输血治疗知情同意书',risk:'输血可发生急性或迟发性免疫性反应、发热、过敏、溶血、循环超负荷、感染传播等风险；即使完成血型鉴定和交叉配血，也不能将风险降至零。',items:['已说明输血目的、血液制品类型及预计输注量','已说明血型鉴定/交叉配血及其局限性','已说明输血反应和监测要求','已说明必要时可能追加输血或其他抢救措施','已说明不输血或延迟输血的风险'],after:'输血期间及之后出现发热、呕吐、呼吸困难、尿色异常、虚脱等应立即处理并记录。'},
 imaging:{title:'影像检查/镇静知情同意书',risk:'X线、超声、CT等检查各有局限。X线/CT涉及电离辐射；镇静/麻醉可能产生呼吸、循环、过敏等风险。影像检查可能无法发现所有病变，也可能需要进一步检查。',items:['已说明检查目的及局限性','已说明可能需要镇静/麻醉及其风险','已说明CT等电离辐射检查的风险与必要性','已说明检查过程中可能因动物不配合而失败或需要调整'],after:'检查后如出现镇静恢复异常、呼吸困难、持续呕吐等应立即就诊。'},
 invasive:{title:'穿刺/活检/病理检查知情同意书',risk:'穿刺、细针采样、活检等侵入性操作可能发生出血、感染、组织损伤、气胸/腹腔出血等与部位相关并发症；样本可能不足、坏死或无法得到明确诊断，必要时需重复取样。',items:['已说明取样部位、目的和预计方式','已说明样本不足/无法诊断的可能性','已说明出血、感染、损伤等风险','已说明病理结果与临床诊断需综合判断'],after:'如术后出现明显出血、呼吸困难、腹部膨大或持续疼痛，应立即就医。'},
 dental:{title:'牙科/口腔操作知情同意书',risk:'牙科操作通常需要镇静/麻醉，存在麻醉风险；拔牙、洁治等操作可能发生出血、牙根/牙槽损伤、口腔疼痛、感染、下颌骨损伤等。术中发现可能需要扩大处理范围。',items:['已说明口腔检查、牙科影像及麻醉的必要性','已说明可能拔牙、牙周治疗或其他追加处理','已说明术后疼痛、饮食和口腔护理要求','已说明病变可能复发，需要长期口腔管理'],after:'按医嘱给予软食、镇痛和复诊。'},
 icu:{title:'ICU/氧疗/生命支持知情同意书',risk:'重症动物存在较高的疾病相关死亡风险。氧疗、机械通气、血管通路、持续监测等均存在设备、操作及治疗相关风险，治疗可能无法逆转原发疾病。',items:['已说明当前危重程度及主要生命危险','已说明氧疗/通气/监测目的和可能风险','已说明可能需要侵入性操作、镇静、输血或CPR','已说明预后存在显著不确定性及费用可能增加'],after:'病情可能快速变化，医院将根据监测结果动态调整方案并按授权方式联系主人。'},
 offlabel:{title:'特殊/超说明书用药知情沟通记录',risk:'当所选药物、物种、适应证、剂量、途径或疗程超出产品批准标签/说明书范围时，存在证据有限、疗效不确定、未知不良反应及责任边界更复杂等风险。',items:['已说明该用药与批准标签的差异（物种/适应证/剂量/途径等）','已说明选择该方案的临床理由及可获得证据','已说明替代药物/治疗方案及其优缺点','已说明潜在不良反应及监测计划','已给予主人提问机会并取得明确同意'],after:'不得将知情同意视为对不规范用药的免责；仍须符合现行法律法规、兽药标签及临床规范。'},
 refusal:{title:'拒绝检查/治疗/建议方案知情确认书',risk:'主人拒绝推荐的检查或治疗后，疾病可能延误诊断、进展、发生不可逆损伤甚至死亡。拒绝不等于疾病风险消失。',items:['已说明推荐检查/治疗的目的和重要性','已说明拒绝后可能发生的后果','已说明合理替代方案（如存在）','主人确认已理解并主动选择拒绝'],after:'如病情发生变化，建议及时复诊。'},
 discharge:{title:'提前离院/自行离院知情确认书',risk:'动物尚未达到推荐出院条件时离院，可能发生病情恶化、治疗中断、用药错误、突发死亡等风险。',items:['已说明当前病情及推荐继续治疗/观察的理由','已说明提前离院的具体风险','已说明带回家的药物、护理和危险信号','主人确认仍选择提前离院'],after:'医院建议出现任何危险信号立即返回医院或前往具备相应救治能力的机构。'},
 body:{title:'动物死亡/遗体处理确认书',risk:'死亡确认后生命活动不可逆终止。遗体保存、火化、无害化处理等方式需根据动物身份、疾病情况和当地相关规定执行。疑似法定报告动物疫病时不得擅自处置。',items:['已确认动物身份、死亡时间及确认兽医师','已说明遗体处理选项及可能费用','已说明疑似传染病时需遵守隔离、报告及无害化处理要求','主人已选择遗体处理方式'],after:'如需遗体转交，双方应记录交接时间、方式和接收人。'}
};
function populateConsent(){const s=$('consentType');if(!s)return;s.innerHTML=Object.entries(CONSENTS).map(([k,v])=>`<option value="${k}">${esc(v.title)}</option>`).join('')}
function collect(){return {
 hospital:'淮南市叮当宠物医院',recordNo:get('caseId'),petName:get('casePetName'),owner:get('caseOwner'),phone:get('casePhone'),species:get('caseSpecies'),breed:get('caseBreed'),age:get('caseAge'),sex:get('caseSex'),weight:get('caseWeight'),
 visitTime:get('mrVisitTime')||iso(),visitType:get('mrVisitType'),vet:get('mrVet'),vetSign:get('mrVetSign'),chief:get('caseChief'),history:get('caseHistory'),past:get('casePast'),prevent:get('casePrevent'),tests:get('caseTests'),results:get('caseResults'),dx:get('caseDx'),ddx:get('caseDDx'),plan:get('casePlan'),advice:get('mrAdvice')||get('caseAdvice'),follow:get('caseFollow'),exam:get('mrExam'),assessment:get('mrAssessment'),disclosure:get('mrDisclosure')
}}
function addRxRow(data={}){const box=$('rxRows');if(!box)return;const row=document.createElement('div');row.className='card rx-row';row.style.margin='8px 0';row.innerHTML=`<div class="grid"><div><label>兽药名称<input class="rx-name" value="${esc(data.name)}"></label><label>规格/制剂<input class="rx-spec" value="${esc(data.spec)}"></label><label>数量<input class="rx-qty" value="${esc(data.qty)}"></label></div><div><label>用法<input class="rx-route" placeholder="口服/皮下/静脉等" value="${esc(data.route)}"></label><label>用量/频次<input class="rx-dose" placeholder="如 10 mg/kg，q12h" value="${esc(data.dose)}"></label><label>疗程/备注<input class="rx-course" value="${esc(data.course)}"></label></div></div><button class="secondary rx-remove" type="button">删除</button>`;row.querySelector('.rx-remove').onclick=()=>row.remove();box.appendChild(row)}
function collectRx(){return [...document.querySelectorAll('.rx-row')].map(r=>({name:r.querySelector('.rx-name').value.trim(),spec:r.querySelector('.rx-spec').value.trim(),qty:r.querySelector('.rx-qty').value.trim(),route:r.querySelector('.rx-route').value.trim(),dose:r.querySelector('.rx-dose').value.trim(),course:r.querySelector('.rx-course').value.trim()})).filter(x=>x.name)}
function finalizeRecord(){const d=collect();if($('mrConfirmed').value!=='yes'||!get('mrSignature')||!get('mrVet')){ $('mrStatus').innerHTML='<div class="bad">必须由实际接诊/诊疗执业兽医师核对并确认，填写医生姓名及电子签名/专用签章标识后才能锁定。</div>';return}const rec={...d,id:uuid(),status:'FINAL',finalizedAt:iso()};localStorage.setItem('VCT_CURRENT_FINAL_RECORD',JSON.stringify(rec));audit('FINALIZE_MEDICAL_RECORD',{recordNo:d.recordNo,vet:d.vet});$('mrStatus').innerHTML='<div class="good">正式门/急诊病历已确认并锁定。后续修改必须形成新版本并保留审计记录。</div>'}
function finalizeRx(){const d=collect();const rx=collectRx();if(!get('mrVet')||!get('mrSignature')||!rx.length){$('rxStatus').innerHTML='<div class="bad">处方必须至少有一项药品，并由执业兽医师确认签名。</div>';return}const out={...d,rx,status:'FINAL',finalizedAt:iso()};localStorage.setItem('VCT_CURRENT_FINAL_RX',JSON.stringify(out));audit('FINALIZE_PRESCRIPTION',{recordNo:d.recordNo,vet:d.vet,count:rx.length});$('rxStatus').innerHTML='<div class="good">处方已锁定。电子处方应按规范打印纸质处方；如电子签名不满足可靠电子签名条件，纸质处方需执业兽医师签名/盖章后方有效。</div>'}
function getFinalOrDraft(){const d=collect();let f=null;try{f=JSON.parse(localStorage.getItem('VCT_CURRENT_FINAL_RECORD')||'null')}catch{};return f&&f.recordNo===d.recordNo?f:d}
function pageShell(title,body,opts={}){const d=collect();return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:${opts.size||'A4'} ${opts.landscape?'landscape':''};margin:12mm}*{box-sizing:border-box}body{font-family:"Noto Sans SC","Microsoft YaHei",Arial,sans-serif;color:#111;font-size:12px;line-height:1.55;margin:0}h1{font-size:20px;text-align:center;margin:0 0 5px}h2{font-size:15px;margin:12px 0 6px;border-bottom:1px solid #222;padding-bottom:3px}h3{font-size:13px;margin:8px 0 4px}.head{text-align:center;border-bottom:2px solid #111;padding-bottom:8px}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;border:1px solid #333;padding:7px;margin-top:8px}.field{border-bottom:1px solid #bbb;min-height:20px}.label{font-weight:bold}.box{border:1px solid #333;padding:7px;white-space:pre-wrap;min-height:34px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sign{display:grid;grid-template-columns:1fr 1fr;gap:30px;margin-top:25px}.footer{margin-top:15px;font-size:10px;color:#444;border-top:1px solid #aaa;padding-top:5px}.stamp{height:65px;border:1px dashed #888;text-align:center;padding-top:20px;color:#777}.small{font-size:10px}.pagebreak{page-break-before:always}table{border-collapse:collapse;width:100%}th,td{border:1px solid #333;padding:5px;vertical-align:top}th{background:#eee}.no-print{margin-bottom:10px}@media print{.no-print{display:none}}`+`</style></head><body><div class="no-print"><button onclick="window.print()">打印</button><button onclick="window.close()">关闭</button></div>${body}<div class="footer">文书生成时间：${esc(iso())}　病历号：${esc(d.recordNo)}　患者：${esc(d.petName)}　说明：本文件由VCT医疗文书引擎根据当前病例数据生成，正式医疗文书以医院确认、签名/签章版本为准。</div></body></html>`}
function recordBody(){const d=getFinalOrDraft();const rows=[['病历号',d.recordNo],['就诊号',d.recordNo],['就诊时间',d.visitTime],['就诊类型',d.visitType],['宠物姓名',d.petName],['物种',d.species],['品种',d.breed],['性别',d.sex],['年龄',d.age],['体重',d.weight+' kg'],['主人',d.owner],['联系电话',d.phone],['接诊/主诊兽医师',d.vet]];return `<div class="head"><div>${esc(d.hospital)}</div><h1>动物门（急）诊病历</h1><div>病例资料打印件</div></div><div class="meta">${rows.map(x=>`<div class="field"><span class="label">${esc(x[0])}：</span>${esc(x[1])}</div>`).join('')}</div><h2>一、主诉</h2><div class="box">${esc(d.chief)}</div><h2>二、现病史</h2><div class="box">${esc(d.history)}</div><h2>三、既往史、用药史及预防保健史</h2><div class="grid2"><div><h3>既往史/用药史</h3><div class="box">${esc(d.past)}</div></div><div><h3>疫苗/驱虫史</h3><div class="box">${esc(d.prevent)}</div></div></div><h2>四、体格检查</h2><div class="box">${esc(d.exam||'本次病例未录入结构化体格检查。')}</div><h2>五、检查及结果</h2><div class="grid2"><div><h3>检查项目</h3><div class="box">${esc(d.tests)}</div></div><div><h3>检查结果</h3><div class="box">${esc(d.results)}</div></div></div><h2>六、诊断及鉴别诊断</h2><div class="grid2"><div><h3>诊断</h3><div class="box">${esc(d.dx)}</div></div><div><h3>鉴别诊断</h3><div class="box">${esc(d.ddx)}</div></div></div><h2>七、诊疗意见、治疗方案及预后</h2><div class="box">${esc(d.assessment||d.plan)}</div><h2>八、医嘱</h2><div class="box">${esc(d.advice)}</div><h2>九、复诊/随访</h2><div class="box">${esc(d.follow)}</div><h2>十、知情沟通记录</h2><div class="box">${esc(d.disclosure)}</div><div class="sign"><div>执业兽医师签名：${esc(d.vet)}<br>电子签名/专用签章：${esc(d.vetSign)}<br>确认时间：${esc(d.finalizedAt||'未锁定')}</div><div class="stamp">医院盖章处</div></div>`}
function rxBody(){const d=getFinalOrDraft();let r=[];try{r=JSON.parse(localStorage.getItem('VCT_CURRENT_FINAL_RX')||'null')?.recordNo===d.recordNo?JSON.parse(localStorage.getItem('VCT_CURRENT_FINAL_RX')).rx:collectRx()}catch{r=collectRx()}return `<div class="head"><div>${esc(d.hospital)}</div><h1>兽医处方笺</h1><div>（打印件）</div></div><div class="meta">${[['主人姓名',d.owner],['病历号',d.recordNo],['开具日期',d.visitTime?.slice(0,10)],['动物种类',d.species],['毛色',d.breed],['性别',d.sex],['体重',d.weight+' kg'],['年龄',d.age]].map(x=>`<div class="field"><span class="label">${esc(x[0])}：</span>${esc(x[1])}</div>`).join('')}</div><h2>初步/临床诊断</h2><div class="box">${esc(d.dx)}</div><h2>Rp.</h2><table><thead><tr><th>兽药名称</th><th>规格/制剂</th><th>数量</th><th>用法</th><th>用量/频次</th><th>疗程/备注</th></tr></thead><tbody>${r.map(x=>`<tr>${['name','spec','qty','route','dose','course'].map(k=>`<td>${esc(x[k])}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="sign"><div>执业兽医师：${esc(d.vet)}<br>电子签名/专用签章：${esc(d.vetSign)}<br>签发时间：${esc(d.finalizedAt||iso())}</div><div class="stamp">动物诊疗机构盖章处</div></div><p class="small">处方应限于当次诊疗结果用药并按现行规范执行。电子处方打印件的有效性取决于可靠电子签名或纸质签名/盖章条件。特殊药品按专门规定管理。</p>`}
function printDoc(kind){const d=getFinalOrDraft();if(kind!=='rx'&&!localStorage.getItem('VCT_CURRENT_FINAL_RECORD')){alert('请先由实际接诊执业兽医师确认并锁定正式病历。');return}if(kind==='rx'&&!localStorage.getItem('VCT_CURRENT_FINAL_RX')){alert('请先确认并锁定处方。');return}let body='';let title='';let opts={size:'A4'};if(kind==='medical'){body=recordBody();title='动物门（急）诊病历';}else if(kind==='rx'){body=rxBody();title='兽医处方笺';opts={size:'A5',landscape:true};}else{body=recordBody()+'<div class="pagebreak"></div>'+rxBody();title='门诊病历及兽医处方';opts={size:'A4'};}const w=window.open('','_blank');if(!w){alert('浏览器阻止了新窗口，请允许弹窗。');return}w.document.open();w.document.write(pageShell(title,body,opts));w.document.close();audit('PRINT_DOCUMENT',{type:kind,recordNo:d.recordNo});}
function printConsent(type){const d=getFinalOrDraft();const c=CONSENTS[type];if(!c)return;const checks=c.items.map((x,i)=>`<div>□ ${esc(x)}</div>`).join('');const body=`<div class="head"><div>${esc(d.hospital)}</div><h1>${esc(c.title)}</h1><div>知情沟通与授权记录</div></div><div class="meta">${[['主人姓名',d.owner],['联系方式',d.phone],['宠物姓名',d.petName],['物种',d.species],['品种',d.breed],['性别',d.sex],['年龄',d.age],['体重',d.weight+' kg'],['病历号',d.recordNo],['就诊时间',d.visitTime]].map(x=>`<div class="field"><span class="label">${esc(x[0])}：</span>${esc(x[1])}</div>`).join('')}</div><h2>一、拟实施的诊疗事项</h2><div class="box">诊疗项目：${esc(c.title.replace('知情同意书',''))}<br>本次病例诊断/问题：${esc(d.dx)}<br>拟实施方案：${esc(d.plan)}</div><h2>二、风险、局限及不确定性</h2><div class="box">${esc(c.risk)}</div><h2>三、已完成的沟通确认</h2><div class="box">${checks}</div><h2>四、替代方案及拒绝/延误后果</h2><div class="box">已向主人说明：如存在替代方案，将根据动物当前病情、证据、可及性及费用等因素说明其优缺点；拒绝、延误或中断推荐检查/治疗可能导致诊断延迟、病情进展、不可逆损伤或死亡。具体替代方案：______________________________<br>主人选择/意见：____________________________________________________________</div><h2>五、费用与追加处置</h2><div class="box">已说明预计费用及可能因病情变化、追加检查、并发症或抢救措施而增加的费用。主人已获知可在治疗前提出费用预算和授权额度。预算/授权说明：____________________________________________________________</div><h2>六、特殊说明</h2><div class="box">${esc(c.after)}<br><br>本同意书用于记录风险告知、沟通和主人授权，不替代病历、处方、诊断书或其他法定文书；也不构成对医疗结果的保证或对依法应承担责任的排除。</div><h2>七、主人确认</h2><div class="box">本人确认：已阅读/听取并理解上述内容；有机会向执业兽医师提问；对拟实施诊疗的目的、主要风险、可能替代方案及拒绝/延误后果已有基本了解，并自愿作出选择。本人提供的病史及信息真实、完整。</div><div class="sign"><div>主人/授权人签名：________________<br>签名日期时间：____________________<br>与动物关系：______________________</div><div>执业兽医师签名：${esc(d.vet)}<br>电子签名/专用签章：${esc(d.vetSign)}<br>告知日期时间：${esc(d.visitTime)}<br><br>医院盖章处</div></div><p class="small">模板版本：VCT-IC-${esc(type)}-5.0-r08　生成时间：${esc(iso())}</p>`;const w=window.open('','_blank');if(!w){alert('浏览器阻止了新窗口，请允许弹窗。');return}w.document.open();w.document.write(pageShell(c.title,body,{size:'A4'}));w.document.close();audit('PRINT_CONSENT',{type,recordNo:d.recordNo});}

function init(){ensureCaseExtras();window.VCTMedical={collect,collectRx,printDoc,printConsent,CONSENTS};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
setTimeout(init,500);
})();
