/* VCT Hospital OS 5.0-r08 — Pharmacy / Pricing / Inventory / Prescription integration
 * Local-first module. Production deployment should replace localStorage with authenticated server DB.
 */
(function(){'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const now=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`};
const uid=()=>crypto?.randomUUID?.()||'VCT-'+Date.now()+'-'+Math.random().toString(16).slice(2);
const K={INV:'VCT_PHARMACY_INV_V1',TX:'VCT_PHARMACY_TX_V1',PRICE:'VCT_PHARMACY_PRICE_V1'};
function read(k,d=[]){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function audit(action,detail={}){const a=read('VCT_MED_AUDIT',[]);a.push({id:uid(),time:now(),action,detail});write('VCT_MED_AUDIT',a.slice(-3000))}
function seed(){
 let inv=read(K.INV,null); if(inv===null){
  inv=[];
  // Seed from the existing 427-drug database as catalog entries, without inventing stock/price.
  try{const catalog=window.VCT_DRUGS||[]; catalog.forEach(d=>inv.push({id:d.id||uid(),name:d.generic_name_zh||d.name||'',brand:(d.brand_names||[])[0]||'',approval:d.label_card?.basic?.approval_number||'',manufacturer:d.label_card?.basic?.manufacturer||'',form:(d.dosage_forms||[])[0]||'',spec:'',unit:'盒',purchasePrice:'',salePrice:'',stock:0,minStock:0,batch:'',expiry:'',location:'',rxClass:'处方药',specialClass:'',status:'启用',source:'data/drugs.json'}))}catch(e){}
  write(K.INV,inv);
 }
}
function nav(){const n=$('nav');if(!n||$('vctPharmacyNav'))return;const b=document.createElement('button');b.id='vctPharmacyNav';b.dataset.v='pharmacy';b.textContent='💊 药房/库存';n.insertBefore(b,n.children[2]||null);const sec=document.createElement('section');sec.id='pharmacy';sec.className='view';sec.innerHTML=`
<div class="card"><h2>💊 药房 / 价格 / 库存 / 发药</h2><div class="info">药物主数据来自现有药物库；价格、批号、效期、库存必须由医院按实际采购/包装录入。处方确认≠自动扣库存；只有实际核发/发药操作才扣减库存。</div></div>
<div class="grid">
<div class="card"><h3>药品资料</h3><label>药品检索<input id="phQ" placeholder="通用名/商品名/批号"></label><div class="toolbar"><button class="primary" id="phSearch">检索</button><button class="secondary" id="phNew">新增库存商品</button></div><div id="phList"></div></div>
<div class="card"><h3>库存预警</h3><div id="phAlerts"></div></div>
</div>
<div class="card"><h3>新增/编辑库存商品</h3><div class="grid"><div>
<label>通用名/商品名<input id="piName"></label><label>商品名<input id="piBrand"></label><label>批准文号<input id="piApproval"></label><label>生产企业<input id="piManufacturer"></label><label>剂型<input id="piForm"></label><label>规格<input id="piSpec" placeholder="如 10mg/片、100mL/瓶"></label><label>包装单位<input id="piUnit" value="盒"></label></div><div>
<label>采购价（元）<input id="piPurchase" type="number" step="0.01"></label><label>销售价（元）<input id="piSale" type="number" step="0.01"></label><label>库存数量<input id="piStock" type="number" step="0.01"></label><label>最低库存<input id="piMin" type="number" step="0.01"></label><label>批号<input id="piBatch"></label><label>有效期<input id="piExpiry" type="date"></label><label>库位<input id="piLocation"></label></div><div>
<label>药品属性<select id="piRxClass"><option>处方药</option><option>非处方药</option><option>特殊药品</option></select></label><label>特殊药品分类<input id="piSpecial" placeholder="麻醉/精神/毒性/放射性等（如适用）"></label><label>状态<select id="piStatus"><option>启用</option><option>停用</option></select></label><input id="piId" type="hidden"><button class="primary" id="piSave">保存药品/库存</button></div></div><div id="piMsg"></div></div>
<div class="card"><h3>库存流水</h3><div class="toolbar"><button class="primary" id="dispenseCurrentRx">💊 核发当前锁定处方并扣库存</button><button class="secondary" id="makeRxCharge">💳 将当前处方生成收费草单</button></div><div class="toolbar"><select id="txType"><option>入库</option><option>盘盈</option><option>盘亏</option><option>报损</option><option>退货</option><option>发药</option></select><input id="txDrug" placeholder="药品ID/名称"><input id="txQty" type="number" step="0.01" placeholder="数量"><input id="txReason" placeholder="原因/关联处方号"><button class="primary" id="txSave">登记流水</button></div><div id="txList"></div></div>`;document.querySelector('main').insertBefore(sec,document.querySelector('main').firstElementChild);b.onclick=()=>{document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));sec.classList.add('active');n.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()}}
function getInv(){return read(K.INV,[])}
function saveInv(a){write(K.INV,a)}
function findDrug(q){q=String(q||'').toLowerCase();return getInv().find(x=>x.id===q||x.name.toLowerCase()===q||String(x.brand).toLowerCase()===q)||getInv().find(x=>[x.name,x.brand,x.id,x.batch].join('|').toLowerCase().includes(q))}
function render(){const q=($('phQ')?.value||'').toLowerCase();let a=getInv().filter(x=>!q||[x.name,x.brand,x.batch,x.id].join('|').toLowerCase().includes(q));$('phList').innerHTML=a.slice(0,100).map(x=>`<div class="card" style="margin:6px 0"><b>${esc(x.name||'未命名')}</b> ${esc(x.brand)} <span class="pill">${esc(x.rxClass)}</span><br>规格：${esc(x.spec)}　批号：${esc(x.batch||'-')}　效期：${esc(x.expiry||'-')}<br>售价：${x.salePrice===''?'未设':esc(x.salePrice+' 元')}　库存：<b>${esc(x.stock)}</b>　最低：${esc(x.minStock)}　库位：${esc(x.location||'-')}<br><button class="secondary" data-edit="${esc(x.id)}">编辑</button></div>`).join('')||'<div class="muted">暂无库存商品。</div>';
 $('phAlerts').innerHTML=a.filter(x=>Number(x.stock)<=Number(x.minStock)|| (x.expiry&&new Date(x.expiry)<new Date(Date.now()+30*864e5))).map(x=>`<div class="warn"><b>${esc(x.name)}</b>：库存 ${esc(x.stock)} / 最低 ${esc(x.minStock)}；效期 ${esc(x.expiry||'-')}</div>`).join('')||'<div class="good">暂无低库存/30日内效期预警。</div>';
 const tx=read(K.TX,[]).slice(0,100);$('txList').innerHTML=tx.map(t=>`<div>${esc(t.time)}　${esc(t.type)}　<b>${esc(t.name)}</b>　${esc(t.qty)}　${esc(t.reason||'')}　库存后：${esc(t.after)}</div>`).join('')||'<div class="muted">暂无流水。</div>';
}
function fill(x){if(!x)return;[['piId',x.id],['piName',x.name],['piBrand',x.brand],['piApproval',x.approval],['piManufacturer',x.manufacturer],['piForm',x.form],['piSpec',x.spec],['piUnit',x.unit],['piPurchase',x.purchasePrice],['piSale',x.salePrice],['piStock',x.stock],['piMin',x.minStock],['piBatch',x.batch],['piExpiry',x.expiry],['piLocation',x.location],['piRxClass',x.rxClass],['piSpecial',x.specialClass],['piStatus',x.status]].forEach(([id,v])=>{if($(id))$(id).value=v??''})}
function dispenseCurrentRx(){const f=read('VCT_CURRENT_FINAL_RX',null);if(!f||!f.rx?.length){alert('没有当前已锁定处方。');return}const a=getInv(),tx=read(K.TX,[]);let changes=[];for(const r of f.rx){const d=a.find(x=>x.id===r.drugId);const q=Number(r.qty||0);if(!d||!q)continue;if(Number(d.stock||0)<q){alert(`库存不足：${r.name}，当前 ${d?.stock??0}，需要 ${q}`);return}changes.push([d,q])}if(!changes.length){alert('当前处方没有关联药房商品，无法自动扣库存；请在处方行选择药房商品后重新锁定处方。');return}for(const [d,q] of changes){const before=Number(d.stock||0);d.stock=before-q;tx.unshift({id:uid(),time:now(),type:'发药',drugId:d.id,name:d.name,qty:q,delta:-q,reason:'处方 '+f.recordNo,before,after:d.stock})}saveInv(a);write(K.TX,tx.slice(0,5000));audit('DISPENSE_PRESCRIPTION',{recordNo:f.recordNo,count:changes.length});alert('当前处方已完成核发登记并扣减库存。');render()}
function makeRxCharge(){const b=read('VCT_CURRENT_RX_BILLING',null);if(!b){alert('请先锁定处方。');return}localStorage.setItem('VCT_CURRENT_BILLING_DRAFT',JSON.stringify({recordNo:b.recordNo,items:b.items.map(x=>({name:x.name,price:Number(x.price||0),qty:Number(x.qty||0),amount:Number(x.price||0)*Number(x.qty||0)})),total:b.total,createdAt:now()}));alert(`已生成收费草单：¥${Number(b.total||0).toFixed(2)}。请在“就诊/收费”模块审核后结算。`)}
function bind(){
 $('dispenseCurrentRx').onclick=dispenseCurrentRx;$('makeRxCharge').onclick=makeRxCharge;$('phSearch').onclick=render;$('phQ').oninput=render;$('phNew').onclick=()=>fill({id:'',name:'',brand:'',approval:'',manufacturer:'',form:'',spec:'',unit:'盒',purchasePrice:'',salePrice:'',stock:0,minStock:0,batch:'',expiry:'',location:'',rxClass:'处方药',specialClass:'',status:'启用'});
 $('phList').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)fill(getInv().find(x=>x.id===b.dataset.edit))};
 $('piSave').onclick=()=>{let a=getInv();const id=$('piId').value||uid();const old=a.find(x=>x.id===id);const x={id,name:$('piName').value.trim(),brand:$('piBrand').value.trim(),approval:$('piApproval').value.trim(),manufacturer:$('piManufacturer').value.trim(),form:$('piForm').value.trim(),spec:$('piSpec').value.trim(),unit:$('piUnit').value.trim()||'盒',purchasePrice:$('piPurchase').value,salePrice:$('piSale').value,stock:Number($('piStock').value||0),minStock:Number($('piMin').value||0),batch:$('piBatch').value.trim(),expiry:$('piExpiry').value,location:$('piLocation').value.trim(),rxClass:$('piRxClass').value,specialClass:$('piSpecial').value.trim(),status:$('piStatus').value,updatedAt:now()};if(!x.name){$('piMsg').innerHTML='<div class="bad">药品名称不能为空。</div>';return}if(old){const idx=a.findIndex(z=>z.id===id);a[idx]={...old,...x}}else{a.unshift(x)}saveInv(a);audit('SAVE_DRUG_INVENTORY',{id,name:x.name,stock:x.stock,salePrice:x.salePrice});$('piMsg').innerHTML='<div class="good">药品价格/库存资料已保存。</div>';render()};
 $('txSave').onclick=()=>{const d=findDrug($('txDrug').value.trim()),q=Number($('txQty').value);if(!d||!q||q<=0){alert('请填写有效药品和数量。');return}let delta=q;if(['盘亏','报损','退货','发药'].includes($('txType').value))delta=-q;const before=Number(d.stock||0),after=before+delta;if(after<0){alert('库存不足，不能形成负库存。');return}d.stock=after;const a=getInv();a[a.findIndex(x=>x.id===d.id)]=d;saveInv(a);const tx=read(K.TX,[]);tx.unshift({id:uid(),time:now(),type:$('txType').value,drugId:d.id,name:d.name,qty:q,delta,reason:$('txReason').value.trim(),before,after});write(K.TX,tx.slice(0,5000));audit('INVENTORY_TX',{drugId:d.id,type:$('txType').value,qty:q,before,after});$('txQty').value='';render()};
}
function syncCatalog(){const a=getInv();if(a.length||!Array.isArray(window.VCT_DRUGS)||!window.VCT_DRUGS.length)return;window.VCT_DRUGS.forEach(d=>a.push({id:d.id||uid(),name:d.generic_name_zh||d.name||'',brand:(d.brand_names||[])[0]||'',approval:'',manufacturer:'',form:(d.dosage_forms||[])[0]||'',spec:'',unit:'盒',purchasePrice:'',salePrice:'',stock:0,minStock:0,batch:'',expiry:'',location:'',rxClass:'处方药',specialClass:'',status:'启用',source:'data/drugs.json'}));saveInv(a);render()}
function init(){seed();nav();bind();render();setTimeout(syncCatalog,1500);setTimeout(syncCatalog,4000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
window.VCTPharmacy={getInventory:getInv,findDrug,saveInventory:saveInv,inventoryKey:K.INV,audit};
})();
