/* VCT Hospital OS 5.0-r08 — Outpatient Full Flow 2.0
 * Workflow: appointment -> customer/pet -> registration -> triage -> queue -> encounter -> medical record -> lab -> imaging -> prescription -> billing -> consent -> follow-up -> callback.
 * This is a local browser workflow layer. Production deployment still requires server DB, RBAC, reliable e-signature, backups, retention and audit infrastructure.
 */
(function(){
'use strict';
const KEY='VCT_OUTPATIENT_FLOW20_V1', AUDIT='VCT_OUTPATIENT_FLOW20_AUDIT_V1', ACTIVE='VCT_ACTIVE_ENCOUNTER_V1';
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
const uid=p=>'VCT'+p+Date.now()+Math.random().toString(16).slice(2,7);
function read(k,def=[]){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(def))}catch{return def}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function audit(action,detail={}){const a=read(AUDIT,[]);a.unshift({id:uid('A'),time:now(),action,detail});write(AUDIT,a.slice(0,5000))}
function nextMrn(){const d=new Date(),p=d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0'),k='VCT_FLOW_SEQ_'+p,n=Number(localStorage.getItem(k)||0)+1;localStorage.setItem(k,n);return 'M'+p+'-'+String(n).padStart(4,'0')}
function active(){return localStorage.getItem(ACTIVE)||''}
function setActive(id){localStorage.setItem(ACTIVE,id)}
function encs(){return read(KEY,[])}
function getEnc(id=active()){return encs().find(x=>x.id===id)}
function upsert(x){const a=encs(),i=a.findIndex(z=>z.id===x.id);if(i<0)a.unshift(x);else a[i]=x;write(KEY,a.slice(0,3000));setActive(x.id);return x}
function baseEncounter(){return {id:uid('E'),mrn:nextMrn(),createdAt:now(),updatedAt:now(),status:'预约/待登记',priority:'普通',appointment:{status:'未预约',time:'',source:'到店'},customer:{name:'',phone:'',wechat:'',notes:''},pet:{name:'',species:'犬',breed:'',coat:'',sex:'未知',age:'',weight:'',microchip:'',allergy:''},registration:{visitType:'初诊',chief:'',source:'到店',operator:'前台',time:now()},triage:{status:'未分诊',score:'',temperature:'',hr:'',rr:'',spo2:'',bp:'',pain:'',dehydration:'',notes:''},queue:{status:'候诊',calledAt:'',startedAt:'',room:'',vet:''},medical:{history:'',past:'',prevent:'',exam:'',tests:'',results:'',dx:'',ddx:'',plan:'',advice:'',follow:'',assessment:'',disclosure:''},labs:[],imaging:[],prescription:[],billing:{items:[],subtotal:0,discount:0,total:0,paid:0,status:'未结算'},consents:[],followups:[],callback:{status:'未安排',date:'',channel:'电话',result:'',notes:''},attachments:[],flags:[],audit:[]}}
function ensureNav(){const nav=$('nav'),main=document.querySelector('main');if(!nav||!main||$('vctFlow20Nav'))return;const b=document.createElement('button');b.id='vctFlow20Nav';b.dataset.v='flow20';b.textContent='🏥 门诊全流程 2.0';nav.insertBefore(b,nav.children[1]||null);const sec=document.createElement('section');sec.id='flow20';sec.className='view';sec.innerHTML=`
<div class="card"><h2>🏥 VCT 门诊全流程 2.0 <small>固定版本 5.0-r08</small></h2><p class="muted">预约 → 客户/宠物档案 → 挂号 → 分诊 → 候诊 → 接诊 → 病历 → 检验 → 影像 → 处方 → 收费 → 知情同意 → 复诊 → 回访。所有环节围绕同一就诊号/病历号关联，前台与医疗文书权限边界保持分离。</p><div id="f20Banner"></div></div>
<div class="card"><div class="toolbar"><button class="primary" data-tab="dashboard">总览</button><button class="secondary" data-tab="appointment">预约/档案</button><button class="secondary" data-tab="registration">挂号/分诊</button><button class="secondary" data-tab="encounter">接诊/病历</button><button class="secondary" data-tab="lab">检验/影像</button><button class="secondary" data-tab="rx">处方/收费</button><button class="secondary" data-tab="consent">知情同意</button><button class="secondary" data-tab="follow">复诊/回访</button></div></div>
<div id="f20dashboard" class="f20tab"></div><div id="f20appointment" class="f20tab" style="display:none"></div><div id="f20registration" class="f20tab" style="display:none"></div><div id="f20encounter" class="f20tab" style="display:none"></div><div id="f20lab" class="f20tab" style="display:none"></div><div id="f20rx" class="f20tab" style="display:none"></div><div id="f20consent" class="f20tab" style="display:none"></div><div id="f20follow" class="f20tab" style="display:none"></div>`;main.insertBefore(sec,main.firstElementChild);b.onclick=()=>showView();renderAll()}
function showView(){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('flow20').classList.add('active');document.querySelectorAll('#nav button').forEach(v=>v.classList.remove('active'));$('vctFlow20Nav').classList.add('active');renderAll()}
function field(id,label,type='text',val='',extra=''){return `<label>${label}<input id="${id}" type="${type}" value="${esc(val)}" ${extra}></label>`}
function currentOrNew(){return getEnc()||baseEncounter()}
function patientCard(x){return `<div class="info"><b>${esc(x.pet.name||'未命名宠物')}</b> · ${esc(x.mrn)} · ${esc(x.customer.name||'未填写主人')} · ${esc(x.pet.species)} ${esc(x.pet.breed)} · ${esc(x.queue.status)}</div>`}
function renderDashboard(){const a=encs(),today=now().slice(0,10),td=a.filter(x=>x.createdAt?.slice(0,10)===today),counts={};td.forEach(x=>counts[x.queue.status]=(counts[x.queue.status]||0)+1);$('f20dashboard').innerHTML=`<div class="grid"><div class="card"><h3>今日门诊</h3><div style="font-size:32px;font-weight:700">${td.length}</div><p class="muted">当前工作日登记/预约记录</p></div><div class="card"><h3>候诊</h3><div style="font-size:32px;font-weight:700">${counts['候诊']||0}</div></div><div class="card"><h3>接诊中</h3><div style="font-size:32px;font-weight:700">${counts['接诊中']||0}</div></div><div class="card"><h3>待回访</h3><div style="font-size:32px;font-weight:700">${a.filter(x=>x.callback.status==='待回访').length}</div></div></div><div class="card"><h3>当前就诊</h3>${getEnc()?patientCard(getEnc()):'<div class="muted">尚未选择就诊。请从预约/档案或挂号列表进入。</div>'}<div class="toolbar"><button class="primary" data-new>＋新建门诊</button><button class="secondary" data-refresh>刷新</button></div></div><div class="card"><h3>最近就诊</h3>${a.slice(0,12).map(x=>`<div class="toolbar" style="justify-content:space-between;border-bottom:1px solid #ddd;padding:8px 0"><span>${esc(x.mrn)} · <b>${esc(x.pet.name)}</b> · ${esc(x.customer.name)} · ${esc(x.queue.status)}</span><button class="secondary" data-open="${x.id}">打开</button></div>`).join('')||'<div class="muted">暂无记录</div>'}</div>`}
function renderAppointment(){const a=encs();$('f20appointment').innerHTML=`<div class="grid"><div class="card"><h3>① 预约 / 建档</h3><div class="two">${field('f20apDate','预约时间','datetime-local',now())}${field('f20apOwner','主人姓名')}</div><div class="two">${field('f20apPhone','手机号','tel')}${field('f20apPet','宠物姓名')}</div><div class="two"><label>物种<select id="f20apSpecies"><option>犬</option><option>猫</option><option>兔/啮齿类</option><option>鸟类</option><option>爬宠/龟鳖</option><option>其他</option></select></label>${field('f20apBreed','品种')}</div><div class="two">${field('f20apCoat','毛色')}${field('f20apAge','年龄')}</div><div class="two"><label>性别<select id="f20apSex"><option>雄</option><option>雌</option><option>雄性绝育</option><option>雌性绝育</option><option>未知</option></select></label>${field('f20apWeight','体重 kg','number','','step="0.01"')}</div><div class="two"><label>预约来源<select id="f20apSource"><option>电话</option><option>微信/小程序</option><option>线上预约</option><option>到店</option><option>转诊</option></select></label>${field('f20apChief','来诊目的/主诉')}</div><button class="primary" data-create-appt>保存预约并生成就诊号</button><div id="f20apMsg"></div></div><div class="card"><h3>② 客户/宠物档案检索</h3><input id="f20apSearch" placeholder="姓名 / 手机号 / 宠物 / 病历号 / 芯片号"><div id="f20apList"></div></div></div>`;renderApList();$('f20apSearch').oninput=renderApList}
function renderApList(){const out=$('f20apList');if(!out)return;const q=($('f20apSearch').value||'').toLowerCase(),a=encs().filter(x=>!q||[x.mrn,x.customer.name,x.customer.phone,x.pet.name,x.pet.microchip].join('|').toLowerCase().includes(q));out.innerHTML=a.slice(0,30).map(x=>`<div class="result" style="margin-top:8px"><b>${esc(x.pet.name||'未命名')}</b> · ${esc(x.customer.name)} · ${esc(x.customer.phone)}<br>${esc(x.mrn)} · ${esc(x.pet.species)} · ${esc(x.pet.breed)} · ${esc(x.appointment.time||x.createdAt)}<div class="toolbar"><button class="secondary" data-open="${x.id}">打开</button><button class="primary" data-register="${x.id}">直接挂号</button></div></div>`).join('')||'<div class="muted">无匹配档案。</div>'}
function createAppointment(){const x=baseEncounter();x.status='预约';x.appointment={status:'已预约',time:$('f20apDate').value||now(),source:$('f20apSource').value};x.customer={name:$('f20apOwner').value.trim(),phone:$('f20apPhone').value.trim(),wechat:'',notes:''};x.pet={...x.pet,name:$('f20apPet').value.trim(),species:$('f20apSpecies').value,breed:$('f20apBreed').value.trim(),coat:$('f20apCoat').value.trim(),sex:$('f20apSex').value,age:$('f20apAge').value.trim(),weight:$('f20apWeight').value};x.registration={...x.registration,chief:$('f20apChief').value.trim(),source:x.appointment.source,time:now()};if(!x.customer.name||!x.pet.name){$('f20apMsg').innerHTML='<div class="bad">主人姓名和宠物姓名为最低建档要求。</div>';return}upsert(x);audit('CREATE_APPOINTMENT',{id:x.id,mrn:x.mrn});$('f20apMsg').innerHTML=`<div class="good">预约已保存：${esc(x.mrn)}</div>`;renderAll();openEncounter(x.id)}
function renderRegistration(){const x=currentOrNew();$('f20registration').innerHTML=`<div class="grid"><div class="card"><h3>③ 挂号 / 分诊</h3>${patientCard(x)}<div class="two"><label>就诊类型<select id="f20rgType"><option>初诊</option><option>复诊</option><option>急诊</option><option>转诊</option><option>体检</option><option>疫苗</option><option>驱虫</option></select></label><label>优先级<select id="f20rgPri"><option>普通</option><option>优先</option><option>急诊</option><option>危急</option></select></label></div>${field('f20rgChief','主诉/来诊目的','text',x.registration.chief)}<div class="two"><label>接诊医生<select id="f20rgVet"><option value="">待分诊</option><option>主诊兽医</option><option>值班兽医</option><option>其他执业兽医</option></select></label><label>诊室/区域<input id="f20rgRoom"></label></div><button class="primary" data-save-reg>保存挂号并进入分诊</button><div id="f20rgMsg"></div></div><div class="card"><h3>分诊记录</h3>${field('f20trTemp','体温 °C','number',x.triage.temperature,'step="0.1"')}${field('f20trHr','HR / bpm','number',x.triage.hr)}${field('f20trRr','RR / min','number',x.triage.rr)}${field('f20trSpo2','SpO₂ %','number',x.triage.spo2)}${field('f20trBp','BP mmHg', 'text',x.triage.bp)}<div class="two">${field('f20trPain','疼痛评分')}${field('f20trDehy','脱水 %')}</div><label>分诊备注<textarea id="f20trNotes">${esc(x.triage.notes)}</textarea></label><button class="primary" data-save-triage>完成分诊并进入候诊</button><div id="f20trMsg"></div></div></div><div class="card"><h3>④ 候诊队列</h3>${renderQueue()}</div>`;if(x.registration.visitType)$('f20rgType').value=x.registration.visitType;if(x.priority)$('f20rgPri').value=x.priority;if(x.queue.vet)$('f20rgVet').value=x.queue.vet}
function renderQueue(){const a=encs().filter(x=>['候诊','已叫号','接诊中'].includes(x.queue.status)).sort((a,b)=>({危急:0,急诊:1,优先:2,普通:3}[a.priority]??9)-({危急:0,急诊:1,优先:2,普通:3}[b.priority]??9));return `<table><thead><tr><th>病历号</th><th>患者/主人</th><th>优先级</th><th>医生</th><th>状态</th><th>操作</th></tr></thead><tbody>${a.map(x=>`<tr><td>${esc(x.mrn)}</td><td><b>${esc(x.pet.name)}</b><br>${esc(x.customer.name)}</td><td>${esc(x.priority)}</td><td>${esc(x.queue.vet||'待分诊')}</td><td>${esc(x.queue.status)}</td><td><button class="secondary" data-call="${x.id}">叫号</button> <button class="primary" data-start="${x.id}">接诊</button></td></tr>`).join('')||'<tr><td colspan="6">暂无候诊</td></tr>'}</tbody></table>`}
function saveReg(){const x=currentOrNew();x.registration.visitType=$('f20rgType').value;x.registration.chief=$('f20rgChief').value;x.priority=$('f20rgPri').value;x.queue.vet=$('f20rgVet').value;x.queue.room=$('f20rgRoom').value;x.queue.status='候诊';x.status='候诊';x.updatedAt=now();upsert(x);audit('REGISTER',{id:x.id,mrn:x.mrn,priority:x.priority});$('f20rgMsg').innerHTML='<div class="good">挂号完成，已进入候诊队列。</div>';renderAll()}
function saveTriage(){const x=currentOrNew();x.triage={status:'已分诊',temperature:$('f20trTemp').value,hr:$('f20trHr').value,rr:$('f20trRr').value,spo2:$('f20trSpo2').value,bp:$('f20trBp').value,pain:$('f20trPain').value,dehydration:$('f20trDehy').value,notes:$('f20trNotes').value};x.queue.status='候诊';x.status='候诊';x.updatedAt=now();upsert(x);audit('TRIAGE',{id:x.id,mrn:x.mrn});$('f20trMsg').innerHTML='<div class="good">分诊已完成。</div>';renderAll()}
function openEncounter(id){const x=getEnc(id);if(!x)return;setActive(id);['caseId','caseSpecies','caseBreed','caseAge','caseSex','caseWeight','casePetName','caseOwner','casePhone','caseChief'].forEach((id,i)=>{const vals=[x.mrn,x.pet.species,x.pet.breed,x.pet.age,x.pet.sex,x.pet.weight,x.pet.name,x.customer.name,x.customer.phone,x.registration.chief];if($(id))$(id).value=vals[i]||''});if($('caseHistory'))$('caseHistory').value=x.medical.history||'';if($('casePast'))$('casePast').value=x.medical.past||'';if($('casePrevent'))$('casePrevent').value=x.medical.prevent||'';if($('caseTests'))$('caseTests').value=x.medical.tests||'';if($('caseResults'))$('caseResults').value=x.medical.results||'';if($('caseDx'))$('caseDx').value=x.medical.dx||'';if($('caseDDx'))$('caseDDx').value=x.medical.ddx||'';if($('casePlan'))$('casePlan').value=x.medical.plan||'';if($('caseAdvice'))$('caseAdvice').value=x.medical.advice||'';if($('caseFollow'))$('caseFollow').value=x.medical.follow||'';x.queue.status='接诊中';x.status='接诊中';x.queue.startedAt=x.queue.startedAt||now();x.updatedAt=now();upsert(x);audit('START_ENCOUNTER',{id:x.id,mrn:x.mrn});showView();switchTab('encounter')}
function pullCase(x){const v=id=>$(id)?.value||'';x.medical.history=v('caseHistory');x.medical.past=v('casePast');x.medical.prevent=v('casePrevent');x.medical.tests=v('caseTests');x.medical.results=v('caseResults');x.medical.dx=v('caseDx');x.medical.ddx=v('caseDDx');x.medical.plan=v('casePlan');x.medical.advice=v('caseAdvice');x.medical.follow=v('caseFollow');x.registration.chief=v('caseChief');x.pet.name=v('casePetName')||x.pet.name;x.customer.name=v('caseOwner')||x.customer.name;x.customer.phone=v('casePhone')||x.customer.phone;x.pet.species=v('caseSpecies')||x.pet.species;x.pet.breed=v('caseBreed')||x.pet.breed;x.pet.age=v('caseAge')||x.pet.age;x.pet.sex=v('caseSex')||x.pet.sex;x.pet.weight=v('caseWeight')||x.pet.weight;x.mrn=v('caseId')||x.mrn;return x}
function renderEncounter(){const x=currentOrNew();$('f20encounter').innerHTML=`<div class="card">${patientCard(x)}<div class="toolbar"><button class="secondary" data-pull-case>从原病例工作台同步</button><button class="primary" data-save-enc>保存当前诊疗</button><button class="primary" data-complete-enc>完成本次门诊</button><button class="secondary" data-open-case>进入原病例工作台</button></div><div id="f20encMsg"></div></div><div class="grid"><div class="card"><h3>⑤ 门/急诊病历</h3>${field('f20mvTime','就诊时间','datetime-local',x.registration.time||now())}<label>现病史<textarea id="f20mh">${esc(x.medical.history)}</textarea></label><label>既往史/用药史<textarea id="f20mp">${esc(x.medical.past)}</textarea></label><label>疫苗/驱虫/预防保健史<textarea id="f20mprev">${esc(x.medical.prevent)}</textarea></label><label>体格检查<textarea id="f20mex" placeholder="T、HR、RR、SpO₂、BP、MM、CRT、精神、体况、脱水、心肺、腹部、泌尿、生殖、神经、肌骨、皮肤等">${esc(x.medical.exam)}</textarea></label></div><div class="card"><h3>诊断与治疗</h3><label>检查项目<textarea id="f20mt">${esc(x.medical.tests)}</textarea></label><label>检查结果<textarea id="f20mr">${esc(x.medical.results)}</textarea></label><label>诊断<textarea id="f20mdx">${esc(x.medical.dx)}</textarea></label><label>鉴别诊断<textarea id="f20mddx">${esc(x.medical.ddx)}</textarea></label><label>诊疗意见/预后<textarea id="f20mass">${esc(x.medical.assessment)}</textarea></label><label>治疗方案<textarea id="f20mplan">${esc(x.medical.plan)}</textarea></label><label>医嘱/监测/危险信号<textarea id="f20madv">${esc(x.medical.advice)}</textarea></label><label>复诊计划<textarea id="f20mfollow">${esc(x.medical.follow)}</textarea></label><label>知情沟通摘要<textarea id="f20mdisc">${esc(x.medical.disclosure)}</textarea></label></div></div>`}
function saveEncounter(){let x=getEnc()||baseEncounter();x.registration.time=$('f20mvTime').value||x.registration.time;x.medical.history=$('f20mh').value;x.medical.past=$('f20mp').value;x.medical.prevent=$('f20mprev').value;x.medical.exam=$('f20mex').value;x.medical.tests=$('f20mt').value;x.medical.results=$('f20mr').value;x.medical.dx=$('f20mdx').value;x.medical.ddx=$('f20mddx').value;x.medical.assessment=$('f20mass').value;x.medical.plan=$('f20mplan').value;x.medical.advice=$('f20madv').value;x.medical.follow=$('f20mfollow').value;x.medical.disclosure=$('f20mdisc').value;x.updatedAt=now();upsert(x);pullToMedicalModule(x);if($('caseSaveBtn')){try{$('caseSaveBtn').click()}catch(e){}}audit('SAVE_ENCOUNTER',{id:x.id,mrn:x.mrn});$('f20encMsg').innerHTML='<div class="good">诊疗数据已保存并与病例工作台同步。</div>';renderAll()}
function pullToMedicalModule(x){if($('mrVisitTime'))$('mrVisitTime').value=(x.registration.time||now()).slice(0,16);if($('mrVisitType'))$('mrVisitType').value=x.registration.visitType||'初诊';if($('mrVet'))$('mrVet').value=x.queue.vet||'';if($('mrExam'))$('mrExam').value=x.medical.exam||'';if($('mrAssessment'))$('mrAssessment').value=x.medical.assessment||'';if($('mrAdvice'))$('mrAdvice').value=x.medical.advice||'';if($('mrDisclosure'))$('mrDisclosure').value=x.medical.disclosure||''}
function completeEncounter(){
 const x=getEnc(); if(!x)return;
 x.queue.status='已完成'; x.status='已完成'; x.updatedAt=now(); x.completedAt=now();
 upsert(x); audit('COMPLETE_ENCOUNTER',{id:x.id,mrn:x.mrn});
 if(x.medical.follow||x.callback.date){x.callback.status='待回访';}
 renderAll(); switchTab('dashboard');
}

function renderLab(){const x=currentOrNew();$('f20lab').innerHTML=`<div class="grid"><div class="card"><h3>⑥ 检验结果</h3><div class="two">${field('f20labTime','采样/报告时间','datetime-local',now())}${field('f20labItem','检验项目')}</div><label>结果<textarea id="f20labResult"></textarea></label><label>参考区间/备注<textarea id="f20labRef"></textarea></label><label>报告人<input id="f20labReporter"></label><button class="primary" data-add-lab>保存检验结果</button></div><div class="card"><h3>影像/PACS记录</h3><div class="two">${field('f20imgTime','检查时间','datetime-local',now())}${field('f20imgItem','检查类型','text','X线/超声/CT/MRI')}</div><label>所见<textarea id="f20imgFind"></textarea></label><label>影像结论<textarea id="f20imgImpression"></textarea></label><label>影像文件/报告位置<input id="f20imgRef" placeholder="文件名、附件标识或PACS编号"></label><label>报告人<input id="f20imgReporter"></label><button class="primary" data-add-img>保存影像记录</button></div></div><div class="card"><h3>已关联检查</h3>${x.labs.map(z=>`<div class="result"><b>检验 · ${esc(z.item)}</b> · ${esc(z.time)}<br>${esc(z.result)}<br><small>报告人：${esc(z.reporter)}</small></div>`).join('')||'<div class="muted">暂无检验记录</div>'}${x.imaging.map(z=>`<div class="result"><b>影像 · ${esc(z.item)}</b> · ${esc(z.time)}<br>${esc(z.impression||z.findings)}<br><small>报告人：${esc(z.reporter)} · ${esc(z.ref)}</small></div>`).join('')||''}</div>`}
function addLab(){const x=currentOrNew();x.labs.unshift({id:uid('L'),time:$('f20labTime').value||now(),item:$('f20labItem').value,result:$('f20labResult').value,reference:$('f20labRef').value,reporter:$('f20labReporter').value});x.medical.tests=[x.medical.tests,$('f20labItem').value].filter(Boolean).join('\n');x.medical.results=[x.medical.results,$('f20labItem').value+': '+$('f20labResult').value].filter(Boolean).join('\n');upsert(x);audit('ADD_LAB',{id:x.id,mrn:x.mrn});renderAll()}
function addImg(){const x=currentOrNew();x.imaging.unshift({id:uid('I'),time:$('f20imgTime').value||now(),item:$('f20imgItem').value,findings:$('f20imgFind').value,impression:$('f20imgImpression').value,ref:$('f20imgRef').value,reporter:$('f20imgReporter').value});x.medical.tests=[x.medical.tests,$('f20imgItem').value].filter(Boolean).join('\n');x.medical.results=[x.medical.results,$('f20imgItem').value+': '+$('f20imgImpression').value].filter(Boolean).join('\n');upsert(x);audit('ADD_IMAGING',{id:x.id,mrn:x.mrn});renderAll()}
function renderRx(){const x=currentOrNew();$('f20rx').innerHTML=`<div class="grid"><div class="card"><h3>⑦ 处方订单</h3><div id="f20rxRows">${x.prescription.map((z,i)=>`<div class="card" style="margin:8px 0"><div class="two">${field('f20rxn'+i,'兽药名称','text',z.name)}${field('f20rxs'+i,'规格/制剂','text',z.spec)}</div><div class="two">${field('f20rxq'+i,'数量','text',z.qty)}${field('f20rxu'+i,'用法','text',z.route)}</div>${field('f20rxd'+i,'用量/频次','text',z.dose)}${field('f20rxc'+i,'疗程/备注','text',z.course)}</div>`).join('')||'<div class="muted">暂无药品。点击新增。</div>'}</div><button class="secondary" data-add-rx>＋新增药品</button> <button class="primary" data-save-rx>保存并同步正式处方</button><div id="f20rxMsg"></div></div><div class="card"><h3>收费/结算</h3><div id="f20billRows">${x.billing.items.map((z,i)=>`<div class="toolbar"><span style="flex:1">${esc(z.name)}</span><input data-bill-name="${i}" value="${esc(z.name)}" style="flex:1"><input data-bill-price="${i}" type="number" step="0.01" value="${z.price}" style="width:100px"><button class="secondary" data-del-bill="${i}">删除</button></div>`).join('')}</div><button class="secondary" data-add-bill>＋收费项目</button><div class="info">应收：${x.billing.total.toFixed(2)}　已收：${x.billing.paid.toFixed(2)}　状态：${esc(x.billing.status)}</div><div class="two">${field('f20Paid','本次收款','number','0','step="0.01" min="0"')}${field('f20Discount','优惠','number',x.billing.discount,'step="0.01" min="0"')}</div><button class="primary" data-settle>更新结算</button><div class="muted">此模块记录收费业务数据，不代表已接入微信/支付宝/医保等真实支付通道。</div></div></div>`}
function addRx(){const x=currentOrNew();x.prescription.push({id:uid('R'),name:'',spec:'',qty:'',route:'',dose:'',course:''});upsert(x);renderAll()}
function saveRx(){const x=currentOrNew();x.prescription=x.prescription.map((z,i)=>({id:z.id,name:$('f20rxn'+i)?.value||z.name,spec:$('f20rxs'+i)?.value||z.spec,qty:$('f20rxq'+i)?.value||z.qty,route:$('f20rxu'+i)?.value||z.route,dose:$('f20rxd'+i)?.value||z.dose,course:$('f20rxc'+i)?.value||z.course})).filter(z=>z.name);upsert(x);pullToMedicalModule(x);if(window.VCTMedical&&$('rxRows')){const box=$('rxRows');box.innerHTML='';x.prescription.forEach(z=>{const row=document.createElement('div');row.className='card rx-row';row.style.margin='8px 0';row.innerHTML='<div class="grid"><div><label>兽药名称<input class="rx-name"></label><label>规格/制剂<input class="rx-spec"></label><label>数量<input class="rx-qty"></label></div><div><label>用法<input class="rx-route"></label><label>用量/频次<input class="rx-dose"></label><label>疗程/备注<input class="rx-course"></label></div></div>';row.querySelector('.rx-name').value=z.name;row.querySelector('.rx-spec').value=z.spec;row.querySelector('.rx-qty').value=z.qty;row.querySelector('.rx-route').value=z.route;row.querySelector('.rx-dose').value=z.dose;row.querySelector('.rx-course').value=z.course;box.appendChild(row);});}audit('SAVE_PRESCRIPTION',{id:x.id,mrn:x.mrn,count:x.prescription.length});$('f20rxMsg').innerHTML='<div class="good">处方数据已保存。请在正式医疗文书中心由执业兽医师审核、签名/签章并锁定。</div>';renderAll()}
function addBill(){const x=currentOrNew();x.billing.items.push({id:uid('B'),name:'诊疗项目',price:0});recalcBill(x);upsert(x);renderAll()}
function recalcBill(x){const s=x.billing.items.reduce((a,b)=>a+Number(b.price||0),0),d=Number(x.billing.discount||0);x.billing.subtotal=s;x.billing.total=Math.max(0,s-d);x.billing.status=x.billing.paid>=x.billing.total&&x.billing.total>0?'已结算':x.billing.paid>0?'部分结算':'未结算'}
function settle(){const x=currentOrNew();x.billing.items.forEach((z,i)=>{z.name=$(`[data-bill-name="${i}"]`)?.value||z.name;z.price=Number($(`[data-bill-price="${i}"]`)?.value||0)});x.billing.discount=Number($('f20Discount')?.value||0);x.billing.paid=Math.min(x.billing.total,Number(x.billing.paid||0)+Number($('f20Paid')?.value||0));recalcBill(x);upsert(x);audit('BILLING_UPDATE',{id:x.id,mrn:x.mrn,total:x.billing.total,paid:x.billing.paid});renderAll()}
function renderConsent(){const x=currentOrNew(),types=window.VCTMedical?.CONSENTS||{};$('f20consent').innerHTML=`<div class="card"><h3>⑧ 知情同意 / 风险沟通</h3><p class="muted">正式模板由医疗文书中心维护；这里负责把同意事项与当前就诊号关联。</p><div class="two"><label>文书类型<select id="f20ConsentType">${Object.entries(types).map(([k,v])=>`<option value="${esc(k)}">${esc(v.title)}</option>`).join('')}</select></label>${field('f20ConsentProject','本次具体项目')}</div><label>已沟通重点<textarea id="f20ConsentNotes"></textarea></label><div class="checklist"><label><input type="checkbox" id="f20ConsentRisk"> 风险/不确定性已说明</label><label><input type="checkbox" id="f20ConsentAlt"> 替代方案及拒绝/延误后果已说明</label><label><input type="checkbox" id="f20ConsentCost"> 费用及追加处置可能已说明</label><label><input type="checkbox" id="f20ConsentQ"> 主人已获得提问机会</label></div><button class="primary" data-save-consent>关联本次沟通</button> <button class="secondary" data-print-consent>打开正式知情同意书</button><div id="f20ConsentList"></div></div>`;renderConsentList(x)}
function renderConsentList(x){const o=$('f20ConsentList');if(o)o.innerHTML='<h4>本次已关联</h4>'+(x.consents.map(z=>`<div class="result"><b>${esc(z.title)}</b> · ${esc(z.time)}<br>${esc(z.project)}<br>${esc(z.notes)}</div>`).join('')||'<div class="muted">暂无</div>')}
function saveConsent(){const x=currentOrNew(),types=window.VCTMedical?.CONSENTS||{},k=$('f20ConsentType').value,c=types[k];const ok=$('f20ConsentRisk').checked&&$('f20ConsentAlt').checked&&$('f20ConsentCost').checked&&$('f20ConsentQ').checked;if(!ok){alert('请先勾选本次已完成的风险、替代方案、费用和提问机会沟通项；如实际未沟通，不应虚假勾选。');return}x.consents.unshift({id:uid('C'),type:k,title:c?.title||k,project:$('f20ConsentProject').value,notes:$('f20ConsentNotes').value,time:now(),status:'沟通已记录'});x.medical.disclosure=[x.medical.disclosure,$('f20ConsentProject').value+'：'+$('f20ConsentNotes').value].filter(Boolean).join('\n');upsert(x);audit('CONSENT_LINK',{id:x.id,mrn:x.mrn,type:k});renderAll()}
function printConsent(){const k=$('f20ConsentType')?.value;if(window.VCTMedical?.printConsent){window.VCTMedical.printConsent(k)}else alert('正式医疗文书模块未加载。')}
function renderFollow(){const x=currentOrNew();$('f20follow').innerHTML=`<div class="grid"><div class="card"><h3>⑨ 复诊计划</h3>${field('f20fuDate','复诊日期','datetime-local',x.callback.date||'')}${field('f20fuChannel','回访渠道','text',x.callback.channel||'电话')}${field('f20fuPlan','复诊/回访计划','text',x.medical.follow)}<label>回访重点<textarea id="f20fuNotes">${esc(x.callback.notes)}</textarea></label><button class="primary" data-save-follow>保存并设为待回访</button></div><div class="card"><h3>⑩ 回访记录</h3><label>回访结果<textarea id="f20cbResult">${esc(x.callback.result)}</textarea></label><label>病情/依从性/不良反应<textarea id="f20cbDetail"></textarea></label><label>下一步<textarea id="f20cbNext"></textarea></label><button class="primary" data-callback>完成本次回访</button></div></div><div class="card"><h3>历史回访</h3>${x.followups.map(z=>`<div class="result"><b>${esc(z.time)}</b> · ${esc(z.channel)} · ${esc(z.result)}<br>${esc(z.detail)}<br>下一步：${esc(z.next)}</div>`).join('')||'<div class="muted">暂无</div>'}</div>`}
function saveFollow(){const x=currentOrNew();x.callback={status:'待回访',date:$('f20fuDate').value,channel:$('f20fuChannel').value,result:x.callback.result||'',notes:$('f20fuNotes').value};x.medical.follow=$('f20fuPlan').value;upsert(x);audit('SCHEDULE_FOLLOWUP',{id:x.id,mrn:x.mrn,date:x.callback.date});renderAll()}
function callback(){const x=currentOrNew();x.followups.unshift({id:uid('F'),time:now(),channel:x.callback.channel,result:$('f20cbResult').value,detail:$('f20cbDetail').value,next:$('f20cbNext').value});x.callback.status='已回访';x.callback.result=$('f20cbResult').value;upsert(x);audit('CALLBACK',{id:x.id,mrn:x.mrn});renderAll()}
function switchTab(name){document.querySelectorAll('.f20tab').forEach(x=>x.style.display='none');$('f20'+name).style.display='block';document.querySelectorAll('#flow20 .toolbar button[data-tab]').forEach(x=>x.className=x.dataset.tab===name?'primary':'secondary')}
function renderAll(){if(!$('flow20'))return;renderDashboard();renderAppointment();renderRegistration();renderEncounter();renderLab();renderRx();renderConsent();renderFollow();const x=getEnc();$('f20Banner').innerHTML=x?patientCard(x):'<div class="warn">当前没有选中的就诊。请先新建预约/挂号或打开历史记录。</div>';}
function newCase(){const x=baseEncounter();upsert(x);audit('NEW_ENCOUNTER',{id:x.id,mrn:x.mrn});renderAll();showView();switchTab('appointment')}
function bind(){
 const root=$('flow20');
 if(!root)return;
 root.addEventListener('click',function(e){
  const b=e.target.closest('button');
  if(!b)return;
  try{
   if(b.dataset.tab){switchTab(b.dataset.tab);return;}
   if(b.dataset.new){newCase();return;}
   if(b.dataset.refresh){renderAll();return;}
   if(b.dataset.open){openEncounter(b.dataset.open);return;}
   if(b.dataset.register){
    openEncounter(b.dataset.register);
    const x=getEnc();
    if(x){x.queue.status='候诊';x.status='候诊';upsert(x);}
    switchTab('registration'); renderAll(); return;
   }
   if(b.dataset.createAppt){createAppointment();return;}
   if(b.dataset.saveReg){saveReg();return;}
   if(b.dataset.saveTriage){saveTriage();return;}
   if(b.dataset.call){
    const x=getEnc(b.dataset.call);
    if(x){x.queue.status='已叫号';x.queue.calledAt=now();upsert(x);audit('CALL_QUEUE',{id:x.id,mrn:x.mrn});renderAll();}
    return;
   }
   if(b.dataset.start){openEncounter(b.dataset.start);return;}
   if(b.dataset.pullCase){let x=getEnc()||baseEncounter();x=pullCase(x);upsert(x);renderAll();return;}
   if(b.dataset.saveEnc){saveEncounter();return;}
   if(b.dataset.completeEnc){completeEncounter();return;}
   if(b.dataset.openCase){
    const x=getEnc();
    if(x){
     pullCase(x);upsert(x);
     document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));
     $('case').classList.add('active');
     document.querySelectorAll('#nav button').forEach(v=>v.classList.toggle('active',v.dataset.v==='case'));
    }
    return;
   }
   if(b.dataset.addLab){addLab();return;}
   if(b.dataset.addImg){addImg();return;}
   if(b.dataset.addRx){addRx();return;}
   if(b.dataset.saveRx){saveRx();return;}
   if(b.dataset.addBill){addBill();return;}
   if(b.dataset.delBill){
    const x=getEnc();
    if(x){x.billing.items.splice(Number(b.dataset.delBill),1);recalcBill(x);upsert(x);renderAll();}
    return;
   }
   if(b.dataset.settle){settle();return;}
   if(b.dataset.saveConsent){saveConsent();return;}
   if(b.dataset.printConsent){printConsent();return;}
   if(b.dataset.saveFollow){saveFollow();return;}
   if(b.dataset.callback){callback();return;}
  }catch(err){console.error(err);alert('操作失败：'+err.message);}
 });
}
function init(){ensureNav();bind();renderAll();switchTab('dashboard')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,250));else setTimeout(init,250);
window.VCTOutpatientFlow20={encounters:encs,getEnc,active,upsert,audit,openEncounter,renderAll};
})();
